docs/components/tasks.md
src/components/mgt-tasks/mgt-tasks.ts

Bugfix 
Touches up Tasks Component documentation,
Fixes initial-id and target-id attributes for Tasks Component

[bugfix] tasks fix for target-id and initial-id

---

src/components/mgt-tasks/mgt-tasks.ts

Feature
Tasks now renders blank during task-load, instead of blinking in pieces of the ui as they are loaded.

[improvement] makes task render nothing during its initial task load

---

src/components/mgt-tasks/mgt-tasks.scss
src/components/mgt-tasks/mgt-tasks.ts
src/components/sub-components/mgt-arrow-options/mgt-arrow-options.ts
src/components/sub-components/mgt-dot-options/mgt-dot-options.ts

- Feature
Added 'Ghost Task' that shows when loading tasks or switching task data-sources,
Refactored parts of the Tasks and Arrow/Dot Options components to better match Lit-Html standards,

[feature] Add 'ghost task' to task loading, and improved tasks lit-html standards compliance

---

docs/providers/msal.md

Closing tag typo
- [n/a] Added tests and all passed
- [n/a] All public classes and methods have been documented
- [ X ] Added appropriate documentation
- [n/a] License header has been added to all new source files
- [n/a] Contains **NO** breaking changes
None

Fix closing tag typo

---

src/components/mgt-tasks/mgt-tasks.ts

- Bugfix
Fixed issue where 'Ghost Task' would appear during any task loading actions
Fixed issue where current target Task Folder would be reset after completing a task using the 'Todo' data Source

[bugfix] Task Component Fixes

---

package.json

Closes # 
Bugfix 
Downgrade of `msal: ^1.0.0`  (which is 1.0.1) to `msal:1.0.1` in package.json to mitigate (but not fix) this issue:
https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/103

[package.json] downgrading msal to default stable version 1.0.0

---

src/providers/MsalProvider.ts

Closes #113 
- Bugfix
The `getAccessToken` method on the MsalProvider currently does not reject the promise and instead returns a `undefined` when a token can not be retreived. This PR updates the method to reject the promise instead.

updated MsalProvider.getAccessToken to reject promise instead of returning undefines

---

src/Graph.ts
src/components/mgt-agenda/mgt-agenda.ts
src/components/mgt-login/mgt-login.ts
src/components/mgt-people/mgt-people.ts
src/components/mgt-person/mgt-person.ts

Closes #30  
- Feature
This PR adds support for the batching capabilities of the Microsoft Graph by batching multiple calls to the Microsoft Graph into a single call. Batching can now be used on all components to optimize code that that is making parallel calls to the graph.
This PR also includes optimizations to the mgt-login and mgt-person components to take advantage of batching and avoid making unnecessary and duplicate calls to the graph

Adding support for batching requests from the graph

---

samples/examples/people-picker.html
samples/teams-tab/auth.html
src/Graph.ts
src/components/components.ts
src/components/mgt-people-picker/mgt-people-picker.scss
src/components/mgt-people-picker/mgt-people-picker.ts
src/utils/utils.ts

[WIP] Adding people picker

---

rollup.config.js

Closes #93  
- Bugfix
This PR is adding a CommonJS bundle as part of the npm package.

Adding a CommonJS bundle

---

index.html
src/Graph.ts
src/components/mgt-agenda/mgt-agenda.ts
src/components/mgt-people-picker/mgt-people-picker.scss
src/components/mgt-people-picker/mgt-people-picker.ts
src/components/mgt-tasks/mgt-tasks.ts

- Feature 
This PR adds few new attributes.
For agenda:
1. group-id - when set, group calendar is used for event data
2. show-max - when set, renders up to show-max number of events
For tasks:
1. hide-header - when set, the header is not rendered

Added group-id and show-max attributes for Agenda, Added hide-header for Tasks

---

.vscode/extensions.json
.vscode/settings.json
package.json
src/providers/TeamsProvider.ts
tslint.json

- Code style update (formatting)
Adding tslint to enforce good styling habits and enforce code documentation

Adding tslint

---

package.json

Updates graph sdk to latest version

Updated graph sdk to 2.0

---

src/components/mgt-people-picker/mgt-people-picker.ts

People picker was not rendering and throwing a null exception in the console

event handler fix for people-picker

---

src/components/mgt-people/mgt-people.ts

Closes #144 
- Feature
The mgt-people component now has support for group-id to display people in a group

Added group-id poroperty for people

---

src/components/mgt-people-picker/mgt-people-picker.scss
src/components/mgt-people-picker/mgt-people-picker.ts

- Bugfix 
1. The cursor now updates appropriately. 
* When hovering on top of the component it changes to the text cursor, even if not hovering of the text input alone (before it only showed the text cursor when hovering over the input)
* When hovering on top of the X in the selected people it changes to pointer
* When hovering on top of people in the dropdown it changes to pointer
2. Hover states
* when hovering on top of people in the dropdown it changes the background of the person
3. Loading view
* when loading data from the graph, it displays ....
4. Templates
* Added the `loading` and the `error` templates for updating the dropdown
5. The selected people are now fully rendered with an mgt-person component (only the image was rendered with the mgt-person before)

People Picker improvements

---

src/Graph.ts
src/components/mgt-tasks/mgt-tasks.ts
src/components/mgt-tasks/task-sources.ts

added filtering planner tasks to a group (#164)

---

src/components/mgt-person-card/mgt-person-card.ts

Fix https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/192.

Fix Person-Card mailto link blocked in iframe.

---

src/components/mgt-person/mgt-person.scss
src/components/mgt-person/mgt-person.ts
src/components/templatedComponent.ts

- Bugfix 
This PR fixes two bugs with the person component:
1. When person component is loading, the initials and photo are were layed out with different sizes and all the content jumped around. This is more apparent when you have multiple person cards where some have images and some don't - the person components do not have the same size.
2. The initials do not resize when the person component is resized

Person - Fixed initials size not updating - fixed alignment of initials and image

---

src/components/mgt-person/mgt-person.scss
src/components/mgt-person/mgt-person.ts

Closes # 204
BugFix
Removes extra image in mgt-person

[person] removing extra image causing issue with initials

---

src/components/mgt-tasks/mgt-tasks.ts

Closes # 213
Bugfix 
Updates mgt-tasks templates to utilize context matching other components. 
```
<mgt-tasks data-source="todo">
<template data-type="task-details">
<div>Owner: {{task.owner}}</div>
</template>
</mgt-tasks>
```

[mgt-tasks] fixing template issue

---

src/components/mgt-people-picker/mgt-people-picker.ts

Closes #194 
Bugfix 
This fixes issue with the `mgt-people-picker` , where the error state would show while loading people, and the loading state doesn't appear to show.

[people-picker] fixing issue with error view showing while loading

---

index.html
src/components/mgt-people-picker/mgt-people-picker.scss
src/components/mgt-people-picker/mgt-people-picker.ts
src/components/mgt-person/mgt-person.ts

Closes #217 
- Bugfix -->
This PR fixes an issue where the person image would not show when the person-details change
This PR also introduces the `selected-person` template

fix for person image not rendering, introduces selected-person template

---

src/components/mgt-agenda/mgt-agenda.ts
src/components/mgt-people/mgt-people.ts
src/components/mgt-tasks/mgt-tasks.ts

This PR removed the `no-people` template from mgt-people as it's a duplicate of `no-data` template. It also standardizes how the no-data template is used in agenda and people

Removed no-people template

---

src/providers/IProvider.ts

Closes # 
- [na ] Project builds (`npm run build`) and changes have been tested in supported browsers (including IE11)
- [na ] All public classes and methods have been documented
- [na ] Added appropriate [documentation](https://github.com/microsoftgraph/microsoft-graph-docs/tree/master/concepts/toolkit)
- [ na] License header has been added to all new source files (`npm run setLicense`)
- [na ] Contains **NO** breaking changes

Fix enum comment error

---

custom-elements.json
src/components/mgt-agenda/mgt-agenda.ts
stories/person.stories.js
stories/personCard.stories.js

Storybook: Adding stories to the person card from examples

---

.storybook/readme.md
custom-elements.json
package.json
readme.md
src/components/mgt-agenda/mgt-agenda.ts
src/components/mgt-login/mgt-login.ts
src/components/mgt-people-picker/mgt-people-picker.ts
src/components/mgt-people/mgt-people.ts
src/components/mgt-person-card/mgt-person-card.ts
src/components/mgt-person/mgt-person.ts
src/components/mgt-tasks/mgt-tasks.ts

Closes #289 
Enable storybook css properties to be generated from component src jsdoc.

Auto generate custom elements json

---

src/components/mgt-person/mgt-person.graph.ts
src/components/mgt-tasks/mgt-tasks.graph.planner.ts
src/components/mgt-tasks/mgt-tasks.graph.todo.ts
src/graph/graph.photos.ts
src/graph/graph.user.ts

- Other... Please describe: License headers
I forgot to run setLicense in the Graph refactor after the latest round of updates.

Adding missing license headers

---

src/components/mgt-login/mgt-login.ts

Contributes to #267 
- Feature
I've restructured the `render*` functions for `mgt-login`:
- `public render()`
- `protected renderButton()` - Render button chrome
- `protected renderButtonContent()` - Render the button content
- `protected renderFlyout()` - Render the flyout chrome. Option here to swap out alternative flyout component.
- `protected renderFlyoutContent()` - Render the flyout content
Docs: https://github.com/microsoftgraph/microsoft-graph-docs/pull/7294

Updated mgt-login with meaningful protected render methods

---

stories/components/agenda.stories.js
stories/components/person.stories.js

Closes # 
Feature 
Add 2 samples to Storybook:
- Get Events for Next Week
- Person Photo Only

add samples for graph explorer integration

---

src/components/mgt-agenda/mgt-agenda.ts
src/components/mgt-get/mgt-get.ts
src/components/mgt-person-card/mgt-person-card.scss
src/components/mgt-person-card/mgt-person-card.ts
src/components/templatedComponent.ts

Contributes to #267 
- Feature
This PR addresses adding protected render methods to the `mgt-person-card` component.
The render methods flow like so:
- `public render()`
- `protected renderNoData()` - Render a state when no person data is available.
- `protected renderPersonDetails(person, image)` - Render the main body of the person card (image, name, icons). 
- `protected renderPersonImage()` - Render the image part of the person details.
- `protected renderPersonName()` - Render the name/title part of the person details.
- `protected renderContactIcons()` - Render the contact icons part of the person details.
- `protected renderAdditionalDetailsButton()` - Render the button to expand the additional details
- `protected …

Restructured render methods in mgt-person-card

---

src/components/mgt-login/mgt-login.scss
src/components/mgt-people-picker/mgt-people-picker.scss
src/components/mgt-person-card/mgt-person-card.scss
src/components/mgt-person/mgt-person.scss
src/components/mgt-tasks/mgt-tasks.scss
src/components/sub-components/mgt-flyout/mgt-flyout.scss
src/components/sub-components/mgt-flyout/mgt-flyout.ts

Closes #255
Closes #343
- Bugfix 
1.  mgt-flyout is now rendered with a position:fixed which allows it to render on top of everything. 
2. improved positioning logic to ensure the mgt-flyout will never be off screen. This means the flyout will now try to resize the content if the window is too small. It accomplishes this by setting the `--mgt-flyout-set-width` css property for children to adapt`
3. mgt-flyout will animate from top or bottom depending on where it is opened on screen
4. mgt-flyout automatically adds the drop shadow to ensure it is consistent across component. All components have been updated
This is an initial PR to update the flyout. Once this PR is merged, I will submit PR to update the components using the flyout (tracked in #353)

Changed flyout to position: fixed

---

src/components/mgt-people-picker/mgt-people-picker.scss
src/components/mgt-people-picker/mgt-people-picker.ts

Re #353 
- Refactoring
This PR updates the people-picker component to leverage the new mgt-flyout features:
* enabled `light-dismiss`
* moved input as anchor of flyout
* update style to hide the overflow when window is too narrow

updated people picker with new flyout

---

src/components/mgt-tasks/mgt-tasks.scss
src/components/mgt-tasks/mgt-tasks.ts

Re #353 
- Refactoring
This PR updates the tasks component to leverage the new mgt-flyout features:
* enabled `light-dismiss`
* width: var(--mgt-flyout-set-width, 350px); to resize the flyout when window is too narrow

updated tasks with new flyout

---

src/components/mgt-person-card/mgt-person-card.scss
src/components/mgt-person/mgt-person.ts

Re #353 
- Refactoring
This PR updates the person and person-card component to leverage the new mgt-flyout features:
* `light-dismiss` enabled for person
* moved person content as anchor of flyout
* added `width: --mgt-flyout-set-width` to person card

updated person card with latest flyout updates

---

src/components/mgt-person/mgt-person.ts

Fixes #360 
This feels like the correct logic to me but I'm happy to be contradicted - the display name stuff is what is erroring
Closes #

Fix initials logic

---

src/components/mgt-person-card/mgt-person-card.ts
src/components/providers/mgt-teams-provider.ts
src/providers/TeamsProvider.ts
src/utils/TeamsHelper.ts

Closes #290 
- Bugfix
`mgt-person-card` has been updated to use the `userPrincipleName` instead of the `mailNickname` value to send messages. In addition, new chat messages are now initiated with a deeplink to Teams instead of the sip protocol.
Docs: [Deep linking to a chat](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/deep-links#deep-linking-to-a-chat)

Fixed messaging logic in person card

---

src/utils/TeamsHelper.ts

Closes #364  
- Bugfix
I broke the chat messaging during my last PR (#357). This adjustment **should** fix it. 
@beth-panx , please take a look and make sure it works for you.

Adjusted access of microsoftTeams global var

---

index.html
readme.md

Closes #369 
Updates Readme with the link to to the `mgt-teams-channel-picker` and within the test page at `index.html`

adding teams-channel-picker to index and link to docs in readme

---

src/components/mgt-person-card/mgt-person-card.scss
src/components/mgt-person-card/mgt-person-card.ts

Closes #380 
Bugfix 
Added linear gradient to handle text overflow for displayName property in person-card. 
Also adds tooltip.

person-card displayName overflow

---

src/components/mgt-get/mgt-get.ts

Closes #392 
- Bugfix
This PR fixes an issue with mgt-get where when the polling rate is set, it does not respect max-pages property
This PR also fixes an issue with mgt-get where the polling-rate would cause the component to rerender even if no data changed.

Fixed issue with polling not respecting max pages

---

src/components/mgt-person/mgt-person.scss
src/components/mgt-person/mgt-person.ts

Closes #387 
- Bugfix
Fixes issue where non English letters do not show up in person initials

Fixed person initials for non English letters 

---

src/components/components.ts
src/components/mgt-agenda/mgt-agenda.ts
src/components/mgt-get/mgt-get.ts
src/components/mgt-login/mgt-login.ts
src/components/mgt-people-picker/mgt-people-picker.ts
src/components/mgt-people/mgt-people.ts
src/components/mgt-person-card/mgt-person-card.ts
src/components/mgt-person/mgt-person.ts
src/components/mgt-tasks/mgt-tasks.ts
src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
src/components/templatedComponent.ts
src/graph/types.ts
src/index.ts

- Code style update (formatting) 
As I'm working on auto generating props and docs for components, I'm finding that some types are not properly defined or incorrect. This PR fixes those type definitions.
In addition, this PR adds the `@fires` doc directive to components that fire events to easily generate event documentation.

ensured types are correct and exported

---

src/graph/graph.user.ts

- Bugfix
I noticed a bug in master where the graph call to get user by query would sometimes return a result with no value. Downstream logic then attempts to pull the id off of the undefined thing and throws an error.
I simply added a check for `value` and `value.length` to ensure that we don't return an array of undefined results.

Fixed bug in query for user

---

src/components/mgt-people-picker/mgt-people-picker.ts

Closes #303 
Feature 
adds new properties to `mgt-people-picker`
1. **placeholder** - allows modifications of placeholder text. Default is "Start typing a name"
2. **selection-mode** - allows developer to specify whether the component supports multiple selected people or just one.   Default is "multiple", "single" being the other option.

people-picker properties placeholder and selection-mode

---

package.json

- Other... Please describe: Dependency update
This PR updates to the latest msal update which fixes an issue when redirect authentication is used along side query parameters.

Updated to latest msal 1.3.1

---

samples/sp-webpart/README.md
samples/sp-webpart/config/package-solution.json
samples/sp-webpart/package.json
samples/sp-webpart/src/webparts/mgtDemo/components/MgtDemo.tsx

- Documentation content changes 
Also updated to use mgt-react

Updated SPFx sample to 1.3 preview and tested with 1.3

---

src/components/mgt-people-picker/mgt-people-picker.scss
src/components/mgt-people-picker/mgt-people-picker.ts

Closes #434 #457 #456 #440 #436 #439 
Bugfix
Bug fixes for the `mgt-people-picker` component as part of 1.3 bug bash. 
e5138db -> #457 
5ad0e53 -> #434 
e6bb13d -> #456 
fda93af -> #440 + **enter & tab key handling**
0bc43f0 -> #436 
0244d93 -> #439

people-picker bugs 

---

src/components/mgt-people-picker/mgt-people-picker.scss
src/components/mgt-people-picker/mgt-people-picker.ts

Reverts microsoftgraph/microsoft-graph-toolkit#461

Revert "people-picker bugs "

---

src/components/mgt-person/mgt-person.ts

- Bugfix
This PR fixes an issue where the image was not rendered when set via `personImage`.

Fixed mgt-person image not getting rendered

---

src/components/mgt-people-picker/mgt-people-picker.scss
src/components/mgt-people-picker/mgt-people-picker.ts
src/components/mgt-person/mgt-person.ts

Closes #454 
Removes additional unnecessary css props and updates comments to be consistent with the implementation of the new component design.

mgt-people-picker updating cssprops to match implementation and documentation

---

src/components/mgt-people-picker/mgt-people-picker.ts

Closes #457  
Bugfix
adds handling to escape the search process if the user uses the left or right arrow keys.

adding handling for left and right arrow key events in search

---

samples/react-app/package.json
samples/react-app/src/App.js

updated react sample to use 1.3 and mgt-react

update react sample to 1.3 and mgt-react

---

src/components/mgt-agenda/mgt-agenda.ts
src/components/mgt-people-picker/mgt-people-picker.scss
src/components/mgt-people-picker/mgt-people-picker.ts
src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts

Closes partially #417 
- Bugfix
Tested: Chrome / Safari / Edge Chromium
Result:
**Add gradients for overflow**
Find design [here](https://www.figma.com/file/tVj3DubCqeip6mhw14Up0j/Microsoft-Graph-Toolkit-(main)?node-id=133%3A1004)
**Restructured channel picker html tree**
before:
after:
**Paddings and Margins cleanup**
- Remove individual margins
- Remove paddings on top and bottom from all children of container
- Add padding top and bottom for container / flex align children
- Replace input with span with attributes to act as input to enable auto width increase

Fix bug for channel picker again :D

---

src/components/mgt-people-picker/mgt-people-picker.ts

Closes #434 
Bugfix 
This was initially a fix intented to fix a flicker pattern when searching in the `mgt-people-picker`. The search functionality and loading has since changed and this is no longer a problem. However, this has unintended effects of causing focus issues with other components that rely on the events. 
Here is the original commit: 
https://github.com/microsoftgraph/microsoft-graph-toolkit/commit/f5c097559c1ebab370a93a8965840c5688e75b34#diff-4b7ee5f7ffb7a1c981093bdb2f2b146f
link to issue: 
https://github.com/microsoftgraph/microsoft-graph-toolkit/pull/336

removing stopPropagation event from people-picker

---

stories/components/personCard.stories.js

Closes # 
Add person card with presence sample to mgt.dev

Add person card with presence sample to mgt.dev

---

src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts

Bugfix 
Changes event tracking in `teams-channel-picker` to @keyup to facilitate search in ie11.

mgt-teams-channel-picker changes event to @keyup for input change

---

src/components/mgt-people-picker/mgt-people-picker.scss
src/components/mgt-people-picker/mgt-people-picker.ts
stories/components/peoplePicker.stories.js

Closes #492 
- Bugfix
Add custom css property to change background color for people list items.

Add background color custom css property for people list items

---

package.json

Closes #479 
- Bugfix
Updated to latest msal update
This update also fixes #479

Updated msal 1.3.2

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/build.yml
CONTRIBUTING.md
azure-pipelines.yml
readme.md

Closes #499 
Updated internal references from "master" to "main".

Updated master to main

---

packages/mgt/README.md

Closes #555 
Simply copied the contents of the README.md from the root folder over to the packages/mgt folder. The will allow NPM to show the correct readme page.

Copied README from root over to MGT folder

---

.storybook/preview-body.html
packages/mgt/src/components/mgt-person-card/mgt-person-card.scss
packages/mgt/src/components/mgt-person/mgt-person.scss
packages/mgt/src/components/mgt-person/mgt-person.ts
stories/components/person.stories.js
stories/components/personCard.stories.js

Closes #524 
- Bugfix 
Implemented according to agreed upon design by team
Added dark mode story as test.

Add presence badge icon css custom property

---

packages/mgt/src/components/mgt-person/mgt-person.scss
packages/mgt/src/components/mgt-person/mgt-person.ts
packages/mgt/src/graph/graph.photos.ts

Closes #545 
- Bugfix
Retrieves contact photos from the contact API instead of from people API. Also fixed the appearance of non 1:1 profile pictures in the person component as seen here:

Fixed incorrect contact photo & person photo size #545

---

packages/mgt/src/components/mgt-tasks/mgt-tasks.ts

Closes #182 
- Feature
I've added a few custom events to make it easier to listen to the changes in mgt-tasks:
- taskChanged: Fires when task metadata has been changed.
- taskAdded: Fires when a new task has been added.
- taskRemoved: Fires when an existing task has been deleted.
As a note, `taskChanged` only fires when a task is marked or unmarked as completed. In the future, this event should also fire when an individual task is updated in other ways. See #218 and #565

Added custom events to mgt-tasks

---

contest.md
readme.md

- Other... 
Adding rules to the code contribution challenge we will launch.
- Added wording in readme linking to official rules
- Added official rules in contest.md file

Add code contribution challenge rules to repo

---

docs/preview/mgt-todo.md
packages/mgt/src/components/mgt-tasks-base/mgt-tasks-base.scss
packages/mgt/src/components/mgt-todo/mgt-todo.ts
stories/components/todo.stories.js

Closes # 
- Bugfix
In this PR I added some docs for the mgt-todo component. I also fixed a few css bugs (some props were being ignored or are no longer relevant) and added a story for easy testing.

Added todo docs and story. Also a few css fixes

---

packages/mgt-element/package.json

I added some extra metadata to the mgt-element package.json to prepare it for publishing.

Update mgt-element package.json

---

samples/react-app/README.md

Closes #642 
Adds simple additional setup information similar to `vue-app`  for the `react-app` sample.

react-app sample additional Readme info

---

samples/angular-app/README.md
samples/angular-app/src/app/app.component.html
samples/angular-app/src/app/app.component.ts
samples/angular-app/src/environments/environment.msal.ts

Closes #639 
Closes #640 
- Bugfix
The sample readme was out of date since it was last updated. The msal config moved from one file to another, so the docs needed to reflect the change. Also, the clientId from the index page was hardcoded in instead of the placeholder `[CLIENT-ID]`.
I also added some code to refresh the view when the user signs in or out.

Updated angular app sample

---

contest.md

Closes #658
- Bugfix
update mgt-core to mgt-help for external questions / comments.

Update contest page with correct mgt alias

---

packages/mgt-react/package.json

Closes #662
Bugfix
Updated types field in package.json for mgt-react to point to the correct entrypoint

Update mgt-react types in package.json from types.d.ts to index.d.ts

---

docs/preview/mgt-element.md
lerna.json
package.json
samples/angular-app/package.json
samples/angular-app/src/app/app.component.ts
samples/angular-app/src/environments/environment.msal.ts
samples/examples/person-card-extensions.html
samples/react-app/package.json
samples/react-app/src/index.js
samples/teams-tab/index.html
samples/vue-app/README.md
samples/vue-app/package.json
samples/vue-app/src/App.vue
samples/vue-app/src/components/LoggedInPage.vue
samples/vue-app/src/components/RecentFileList.vue

Closes #595 
- Feature
In this PR I've updated the vue sample to use the local mgt packages.

Updated samples to use local package dependencies

---

packages/mgt/src/components/mgt-person-card/sections/mgt-person-card-organization/graph.organization.ts

Closes #624 
- Bugfix 
I added a filter to the person-card organization section to filter out non-people entities.

Filtering out non-person entities in person card organization

---

packages/mgt/src/graph/graph.presence.ts

Closes #523 
Feature
Modifying the `graph.presence.ts` service to utilize `POST /communications/getPresencesByUserId` instead of batching to get multiple users presence.

Adding getPresenceByUserId on mgt-people

---

packages/mgt-react/readme.md

Improve syntax quality
Closes #

Fix broken react code

---

.storybook/main.js
readme.md

Closes #590 
- Bugfix
Updated storybook badge. You can double check this on the readme.md of this branch.
Removed addons as investigation of memory leak goes on...

Update storybook setup (udpate badge, remove addons)

---

packages/mgt/src/providers/MsalProvider.ts

Closes #693 
- Bugfix
>Note: I didn't use `??` because the prettier version we are using does not support it - we will update it once we've update prettier (#560)

Fixed setting storeAuthStateInCookie in MsalProvider

---

packages/mgt-react/src/generated/react.ts
packages/mgt/src/components/mgt-person-card/mgt-person-card.scss
packages/mgt/src/components/mgt-person-card/mgt-person-card.ts
packages/mgt/src/components/mgt-person/mgt-person.scss
packages/mgt/src/components/mgt-person/mgt-person.ts
stories/components/person.stories.js

- Feature
This PR adds a three line to the person component. This was done to support the requirements in the person card which renders three lines. By using the person component in the person card, we can remove duplicate and unnecessary code and make the person component even better.
This PR also removes the deprecated `showName` and `showEmail`

Person - added support for a 3rd line

---

packages/mgt-react/src/generated/react.ts
packages/mgt/src/components/mgt-tasks/mgt-tasks.ts

- Bugfix
This PR fixes the tasks `dataSource` type in mgt-react by updating the ts docs in the source.

[React][Tasks] Fixed dataSource type

---

packages/mgt/src/components/mgt-people-picker/mgt-people-picker.ts

Closes #672 
Bugfix 
Only sets input value if search needs to be debounced, so if search is skipped for deletion of a character, the previous debounced search doesn't preserve state and overwrite. Avoids the possibility of a user changing search query quickly if they are a fast typer.

fix for debounce issue removing characters

---

packages/mgt/src/components/mgt-people-picker/mgt-people-picker.ts

- Bugfix
While reviewing other PRs, I noticed the loading ring was broken and only was shown once the first time the flyout was open. This PR fixed that issue by moving the logic for setting `this.showLoading` inside the debounce function. 
This PR also refactors how the input value is set by never setting the input during render but only when necessary to clear it.

[PeoplePicker] Fixed showLoading and minor refactoring

---

packages/mgt/src/components/mgt-people-picker/mgt-people-picker.scss

Closes #769
Bugfix
consolidates some of the css + bug fix for highlight search text

updating highlight search text

---

packages/mgt-components/src/components/mgt-person-card/mgt-person-card.scss
packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts
packages/mgt-components/src/components/mgt-person-card/sections/mgt-person-card-contact/mgt-person-card-contact.scss
packages/mgt-components/src/components/mgt-person-card/sections/mgt-person-card-contact/mgt-person-card-contact.ts
packages/mgt-components/src/components/mgt-person-card/sections/mgt-person-card-files/mgt-person-card-files.scss
packages/mgt-components/src/components/mgt-person-card/sections/mgt-person-card-files/mgt-person-card-files.ts
packages/mgt-components/src/components/mgt-person-card/sections/mgt-person-card-organization/mgt-person-card-organization.scss
packages/mgt-components/src/components/mgt-person-card/sections/mgt-person-card-organization/mgt-person-card-organization.ts
packages/mgt-components/src/components/mgt-person-card/sections/mgt-person-card-profile/mgt-person-card-profile.scss
packages/mgt-components/src/components/mgt-person-card/sections/mgt-person-card-profile/mgt-person-card-profile.ts

Closes #750 
Feature 
Adds css and necessary functional changes to support RTL directionality for the 2.0 version of the `mgt-person-card`.
**testing notes:**
1) phone numbers in rtl languages are still displayed ltr:
https://github.com/microsoftgraph/microsoft-graph-toolkit/compare/nivogt/cardRTL?expand=1#diff-b1fc856bdcc4a0107b3bad7ae542c4a9d8c7cab8a027670e5a05a90a3324899aR238-R247
2) In the Organization section, clicking on a contact will lead the user to that contact's person card. By default the CSS is mirrored but the arrow svg aren't, producing the following result:
The Svgs have been mirrored so that the sequence is instead:
Open to ideas though. @tramadon will take a look if he has time.

rtl for person-card and subsequent sections

---

packages/mgt-components/src/components/mgt-todo/graph.todo.ts
packages/mgt-components/src/components/mgt-todo/mgt-todo.ts

Closes #733 
- Other... update to use v1 graph vs beta graph.

Update todo endpoint to v1

---

samples/examples/simple-provider.html

Fix for Simple Provider Sample not working

---

packages/mgt-components/src/graph/graph.people.ts
packages/mgt-components/src/utils/Utils.ts
samples/examples/simple-provider.html

Closes #752 
Bugfix 
Added a util function that extracts an email address from a string

Invalid email #752

---

samples/sp-webpart/README.md

Updates API access path in the admin portal for the SPFx readme.

updating path to find api access in spfx readme

---

packages/mgt-react/package.json
packages/mgt-react/scripts/generate.js
packages/mgt-react/src/generated/react.ts

Closes #812 
Closes #715  
This PR updates the dependency for mgt-react from @microsoft/mgt to @microsoft/mgt-components
This PR also exports mgt-element and mgt-component types used by the components

mgt-react - changed dependency from mgt to mgt-components

---

packages/mgt-components/src/components/mgt-person/mgt-person.ts

This reverts commit 8e7390a1c46b1182ebcda6257fbe12ed803b8cc2.

Revert this pr #860

---

packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts
packages/mgt-components/src/components/mgt-person/mgt-person.ts
packages/mgt-react/src/generated/react.ts
stories/components/person.stories.js

Closes #826 
Feature
Added line click events `line1clicked`, `line2clicked`, and `line3clicked` to `mgt-person` component. Also added a story `personLineClickEvents` to show the usage.

Adds line click events to mgt-person

---

samples/proxy-provider-asp-net-core/Controllers/ProxyController.cs

Closes #885  
Bugfix
Other... Please describe:
Includes ConsistencyLevel Header in mgt-netcore proxy example
Added the consistencylevel header to the filter for required headers so that it is not stripped out by the proxy.

Include consistencylevel header in Proxy

---

.github/workflows/push.yml
packages/mgt-components/src/components/mgt-person/mgt-person.ts
stories/components/person.stories.js

Closes #872 
Feature
adds property:
`avatar-type`
NOTE: displayName property is required for initials
eg:
```<mgt-person person-query="me" avatar-type="initials"></mgt-person>```
``` <mgt-person person-query="me" avatar-type="photo"></mgt-person>```
``` <mgt-person person-query="me"></mgt-person>```
if avatar-type="initials" is chosen, the `getUser` or `getUsersByUserIds` calls will be used (depending if id is supplied or person-query="me") to gather personDetails.

avatar-type to force render state on mgt-person

---

index.html
packages/mgt-components/src/components/mgt-person/mgt-person.ts
packages/mgt-react/src/generated/react.ts
stories/components/person.stories.js

Closes #799 
Feature
Adds fallback details if user is not found in graph
<mgt-person person-query="bill gates" fallback-details={{email: "my@email.com", displayName: "Bill Gates"}}></mgt-person>

[mgt-person] Add fallback value when no person/user is found in graph

---

packages/providers/mgt-msal-provider/src/MsalProvider.ts
packages/providers/mgt-msal-provider/src/mgt-msal-provider.ts

Closes #911 
Feature 
adds domainHint to msal provider
ref:
https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso

msal provider support for domainHint

---

packages/mgt-components/package.json
packages/mgt-components/src/components/mgt-person-card/sections/mgt-person-card-profile/mgt-person-card-profile.ts
packages/mgt-react/package.json
packages/mgt-react/src/generated/react.ts

There is now a new npm package for the Microsoft Graph beta types and we can update our reference in order fix any issue folks are having with installing the package if they don't have git installed.

Updated to use microsoft graph types beta from npm

---

packages/mgt-components/src/components/mgt-agenda/mgt-agenda.ts

Updates Agenda to correctly handle UTC dates. Closes #937

---

packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.graph.ts
packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts

Closes #935 
Feature
Teams channel picker - change scopes in API calls

Update scopes needed to Channel.ReadBasic.All and Team.ReadBasic.all

---

packages/providers/mgt-msal-provider/src/MsalProvider.ts
packages/providers/mgt-msal-provider/src/mgt-msal-provider.ts

Merging next/domainHint to main

msal provider support for domainHint (#925)

---

packages/providers/mgt-msal-provider/src/MsalProvider.ts
packages/providers/mgt-msal-provider/src/mgt-msal-provider.ts

Closes #
Feature
Allows developer to specify MSAL parameter "prompt", for further configuration. 
Unless specified, defaults to "select_account"

msal custom parameter "prompt" 

---

packages/mgt-components/src/components/mgt-person/mgt-person.scss
stories/components/person.stories.js

Closes #946 
Bugfix
Provides a relative anchor for the presence icon. Adds some additional stories for coverage. 
**important to test all person-scenarios + multiple browsers for this one.**

[mgt-person][presence] small avatar presence fix

---

stories/components/fileList.stories.js

- Other: add story to showcase how to build breadcrumbs nav to open folders using mgt-file-list

Add breadcrumb story for mgt-file-list

---

packages/mgt-element/src/utils/Batch.ts

Closes #958 
Bugfix
adds additional expected response type for profile images from legacy accounts, progressive jpegs. 
Credit: 
@latonita

[Batch]update batch to accept pjpeg images

---

packages/providers/mgt-msal-provider/src/MsalProvider.ts

Sets optional prompt feature for msalprovider, fixes issue where it was not set.

[msal] optional prompt and fix 

---

packages/mgt-components/src/components/mgt-person/mgt-person.ts

Closes #1000
Bugfix
Adds quick check to fetch avatar image only if `avatar-type="photo"`
*note*: tested common scenarios seemed fine, make sure to handle caching

[mgt-person] avatar-type check for photo fetching

---

package.json
packages/mgt-components/src/components/mgt-agenda/mgt-agenda.graph.ts
packages/mgt-components/src/components/mgt-get/mgt-get.ts
packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
packages/mgt-components/src/components/mgt-person-card/mgt-person-card.graph.ts
packages/mgt-components/src/components/mgt-person/mgt-person.ts
packages/mgt-components/src/components/mgt-tasks/mgt-tasks.graph.planner.ts
packages/mgt-components/src/components/mgt-tasks/mgt-tasks.ts
packages/mgt-components/src/components/mgt-todo/mgt-todo.ts
packages/mgt-components/src/graph/graph.groups.ts
packages/mgt-components/src/graph/graph.people.ts
packages/mgt-components/src/graph/graph.user.ts
packages/mgt-components/src/utils/Utils.ts
packages/mgt-element/src/providers/Providers.ts
packages/mgt-element/src/utils/GraphPageIterator.ts
packages/providers/mgt-sharepoint-provider/src/SharePointProvider.ts

- Code style update (formatting)
This PR updates prettier from 1.x to 2.x which supports additional TypeScrypt features such as [optional chaining, nullish coalescing](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining), etc.

Updated to Prettier 2.x to support additional TS features

---

packages/mgt-components/src/components/mgt-file-list/mgt-file-list.ts
packages/mgt-components/src/components/mgt-file/mgt-file.ts
packages/mgt-components/src/graph/cacheStores.ts
packages/mgt-components/src/graph/graph.files.ts
packages/mgt-element/src/utils/Cache.ts
packages/mgt-element/src/utils/GraphPageIterator.ts
packages/mgt-react/src/generated/react.ts
stories/components/fileList.stories.js

Closes #980 #981 
- Feature -
Added caching for files and filelists.

Cache for mgt-file and mgt-file-list

---

packages/mgt-components/src/components/mgt-person-card/sections/mgt-person-card-profile/mgt-person-card-profile.ts

Closes #1003 
Bugfix 
Adds handling for company details if not provided. Makes sure `position.details` exists as well.

additional handling for profile work details

---

packages/mgt-components/src/components/mgt-file-list/mgt-file-list.ts
packages/mgt-components/src/components/mgt-file-list/strings.ts
packages/mgt-components/src/components/mgt-file/mgt-file.ts
packages/mgt-components/src/components/mgt-file/strings.ts

Closes #990 #989
Feature
Adds 3 localized strings for the mgt-file and mgt-file-list components. 
Easy test module:
```js
<script type="module">
import { LocalizationHelper } from '@microsoft/mgt';
LocalizationHelper.strings = {
_components: {
'file-list': {
showMoreSubtitle: 'Show more Please!'
},
file: {
modifiedSubtitle: 'changed',
sizeSubtitle: 'testSize'
}
}
};
</script>
```

[mgt-file][mgt-file-list] Localization

---

packages/mgt-components/src/components/mgt-person/mgt-person.theme.scss
packages/mgt-components/src/components/mgt-person/mgt-person.ts
packages/mgt-components/src/graph/graph.presence.ts

Closes #904
Closes #1004
- Bugfix
- Update presence API to v1 from beta
- Fixed case 'appear offline' from Teams status
You can test with storybook mgt-person personPresenceDisplayAll story.

Update presence apis from beta to v1

---

packages/mgt-element/src/utils/Cache.ts

Bug fix for Mozilla Private Browsing

---

packages/mgt-components/src/components/mgt-login/mgt-login.ts
packages/mgt-element/src/providers/IProvider.ts
packages/providers/mgt-msal2-provider/src/Msal2Provider.ts

Changes to mgt-login to store person image

---

packages/mgt-components/src/components/mgt-login/mgt-login.ts
packages/mgt-element/src/providers/IProvider.ts
packages/providers/mgt-msal2-provider/src/Msal2Provider.ts

Changes to mgt-login part 2

---

packages/mgt-components/src/components/mgt-login/mgt-login.ts
packages/mgt-element/src/providers/IProvider.ts
packages/providers/mgt-msal2-provider/src/Msal2Provider.ts

Addressed PR comments 

---

package.json

rolls back rollup to working version for build

fix rollup by rolling back

---

packages/mgt-components/src/components/mgt-person/mgt-person.scss
packages/mgt-components/src/components/mgt-person/mgt-person.ts

Closes #1059
Feature
Gives users the ability to set custom cursor for avatar hover. 
Nil

[mgt-person] add --avatar-cursor custom CSS style

---

.storybook/main.js
.storybook/preview.js
stories/components/agenda/agenda.a.js
stories/components/agenda/agenda.properties.js
stories/components/agenda/agenda.style.js
stories/components/agenda/agenda.templating.js

This PR adds additional stories for agenda per #1128

[mgt.dev] Added additional agenda stories

---

packages/mgt-components/src/components/mgt-file-list/mgt-file-list.ts

Closes #1148 
- Bugfix 
template needs an id to avoid collision

[mgt-file-list] template bug fix

---

packages/mgt-components/src/components/mgt-person-card/mgt-person-card.scss
packages/mgt-components/src/components/mgt-person-card/mgt-person-card.theme.scss
packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts
packages/mgt-components/src/components/mgt-person/mgt-person.theme.scss
stories/components/personCard/personCard.a.js

Closes #1138 & #1135 
Bugfix
Reintroduces additional properties so the following are valid css + themes:
1)  mgt-person `color`  
```css
mgt-person{
/* equivalent */ 
--color-sub1: blue; 
--color: blue;
/* additional valid */ 
--line2-color: blue; 
--color-sub1: blue;
--color-sub2: blue; 
}
```
2) fixes `mgt-person-card` line properties:
```css
mgt-person-card{
--person-card-display-name-font-size: 40px;
--person-card-display-name-color: #a00808;
--person-card-title-font-size: 20px;
--person-card-title-color: #a07c05;
--person-card-subtitle-font-size: 40px;
--person-card-subtitle-color: #9c1515;
}
```
3) fixes person rtl story
4) `mgt-person-card` js documents `expanded` Event #1135

[mgt-person-card] css custom properties 

---

stories/components/agenda/agenda.a.js
stories/components/file/file.a.js
stories/components/fileList/fileList.a.js
stories/components/login/login.stories.js
stories/components/people/people.a.js
stories/components/person/person.js

Updates various component RTL stories with the proper implementation.

rtl implementation fix

---

packages/mgt-element/src/utils/TemplateHelper.ts
stories/samples/templating.stories.js

Closes #1217
- Bugfix
Extends regex in `TemplateHelper` to include `,'"\s` so that it's possible to call functions with multiple arguments inside templates. The new regex also allows arguments to be constants.
Adjusted one of the existing stories to verify that everything is working as intended.

Fixes issue with calling functions with multiple args in templateContext. Closes #1217

---

samples/teams-sso-node/package.json
samples/teams-sso-node/tsconfig.json

Refactoring (no functional changes, no api changes)
I removed some unnecessary lines in the tsconfig, since we are referencing the sample from the docs.
I also bumped the msal-node version from alpha to 1.3.0.

Simplified tsconfig and bumped msal-node from alpha

---

packages/mgt-components/src/components/mgt-file-list/mgt-file-upload/mgt-file-upload.ts

Closes # 
Bugfix 
Include validation when driveitem is empty to display associated error message.

mgt-file-upload Include validation when driveitem is empty to display failed message.

---

packages/mgt-components/src/components/mgt-file-list/mgt-file-upload/mgt-file-upload.ts
packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts
packages/mgt-components/src/components/mgt-person/mgt-person.ts
packages/mgt-components/src/utils/FluentComponents.ts
stories/components/peoplePicker/peoplePicker.a.js

- Merged main into next/fluentui
- Updated fluent ui registration code

Merge main and update fluentui registration

---

packages/mgt-components/src/components/mgt-get/mgt-get.ts

Extends mgt-get with no-data template. Closes #1223

---

.storybook/manager-head.html

Closes #1084 
Closes #1096  
Bugfix
Hides the shortcut button so as to avoid accessibility issues.

hides shortcut button

---

packages/mgt-components/src/components/mgt-person-card/sections/mgt-person-card-contact/mgt-person-card-contact.ts
stories/components/personCard/personCard.properties.js

Closes #1405 
Bugfix
Fixes incorrect hyperlink on business phone contact section when a user has two contact numbers.

[person-card] fix incorrect contact hyperlinks

---

index.html
package.json
packages/mgt-components/src/components/mgt-tasks-base/mgt-tasks-base.ts

Closes #1109 
Closes #1107 
Bugfix
This PR makes **mgt-todo** accessible via keyboard.

[accessibility] mgt-todo

---

.storybook/manager-head.html
.storybook/theme.js
package.json

#1086 
Bugfix
Updates Storybook theme and fixes luminosity ratio.

updates storybook theme

---

.github/ISSUE_TEMPLATE/support-question.md

Closes # 
Typo fixed.
Just a word duplication fix in the issue template.
This PR is just a typo fixed. I am working on a feature (I will submit another PR) and I discovered the typo, that is why I submit this PR.

Remove duplicated word in the issue template

---

.storybook/manager-head.html

fixes h1 tag styling

---

.github/workflows/next.yml
.github/workflows/pr.yml
.github/workflows/push-release.yml
.github/workflows/push.yml
.github/workflows/storybook.yml

Adding the Storybook automatic deployment for new PRs.

Adding the storybook auto deployment

---

packages/mgt-components/src/components/mgt-person/mgt-person.ts

Closes #1460  
Bugfix
Fixes loading images while passing personImage as part of the person-details OR as a person-image

[person] Fixes image load while using person-image

---

packages/mgt-components/src/graph/graph.userWithPhoto.ts

Closes #1456 
- Bugfix
Catch and silently discard error messages emanating from non-existent user IDs/

Catch and silently throw the errors when the user ID for a person does not exist in Azure AD

---

packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts

Closes #1505 
Bugfix
Fixes inherit-details functionality on mgt-person-card

[person-card] Fixes inherit-details functionality

---

packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts

Closes #1117
Bugfix
The people picker has a dropdown of filtered people based on the input. If narration is on, and you navigate to the input with the flyout showing:
1) Ensure scan mode is off (caps lock + space)
2) Use arrows to navigate 
It should narrate the filtered names individually depending on the focus (narration focus and HTML focus).
To move back to the input, you must shift-tab (backwards order) away from the flyout. See the video for demonstration:
https://user-images.githubusercontent.com/11411686/152070139-6de32a01-0b59-498e-b8ad-06ec633d619a.mp4

[people-picker] Accessibility, narration of drop down people

---

stories/components/agenda/agenda.a.js
stories/components/file/file.a.js
stories/components/fileList/fileList.a.js
stories/components/people/people.a.js
stories/components/peoplePicker/peoplePicker.a.js
stories/components/person/person.style.js
stories/components/personCard/personCard.a.js
stories/components/teamsChannelPicker/teamsChannelPicker.a.js
stories/feedback.stories.mdx
stories/overview.stories.mdx

- Change all custom hierachy paths to use `/`. Storybook v6+ has `/` as the sole separator and it's not configurable. [See here](https://github.com/storybookjs/storybook/blob/master/MIGRATION.md#simplified-hierarchy-separators)
- Change doc block imports from `@storybook/addon-docs/blocks` to `@storybook/addon-docs`. This makes it possible for bundlers to automatically choose the ESM or CJS version of the library depending on the context. [See here](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-scoped-blocks-imports)

Storybook: update deprecated code in v6+

---

.storybook/addons/codeEditorAddon/codeAddon.js
package.json

Revert "Added support for using real accessTokens in mgt.dev"

---

.storybook/addons/codeEditorAddon/codeAddon.js

Revert "Added support for using real accessTokens in mgt.dev" (#1519)

---

packages/providers/mgt-teamsfx-provider/package.json

[mgt-teamsfx-provider] Update teamsfx SDK version to support new authentication flow

---

packages/mgt-components/src/components/mgt-file-list/mgt-file-list.ts
stories/components/fileList/fileList.templating.js

Closes #1484  
Bugfix
Adds an itemClick event in file rendered template
Adds an example in sample react-app

[file] Adds click event in file custom template

---

packages/providers/mgt-msal2-provider/package.json
packages/providers/mgt-teams-msal2-provider/package.json
samples/angular-app/package.json

Closes #1491  
- Bugfix
To test, I had to delete the browser cookies and local storage.

Update the msaljs-browser version to v2.22.0

---

packages/mgt-element/src/utils/Batch.ts

Closes #1608 
- Bugfix
A simple extension of the list of image formats  that need a data:image/format;base64 prepended to correctly render in browsers.

Fix display of png images

---

packages/providers/mgt-teamsfx-provider/package.json

[mgt-teamsfx-provider] update teamsfx to 0.6.0-beta.0 for internal usage

---

samples/vue-app/package.json

Closes # 
Override the sabotaged version of node-ipc
https://snyk.io/blog/peacenotwar-malicious-npm-node-ipc-package-vulnerability/

[security]override the sabotaged version of node-ipc

---

packages/providers/mgt-teamsfx-provider/package.json

[mgt-teamsfx-provider] TeamsFx SDK use range version

---

packages/providers/mgt-teamsfx-provider/package.json

Update teamsfx sdk version to 0.7.0-beta.0 for GA testing

---

packages/providers/mgt-teamsfx-provider/README.md
packages/providers/mgt-teamsfx-provider/package.json

[mgt-teamsfx-provider] Update for GA

---

packages/mgt-spfx/.yo-rc.json
packages/mgt-spfx/config/package-solution.json
packages/mgt-spfx/package.json

Closes # n/a
- Other... Updates mgt-spfx to SPFx@1.14.0

Updates mgt-spfx to SPFx@1.14.0

---

packages/mgt/src/bundle/mgt-loader.js

Fix outerHTML reference for the tag

---

packages/providers/mgt-teamsfx-provider/package.json

[mgt-teamsfx-provider] update peer dependency to support teamsfx sdk 1.x.x

---

stories/overview.stories.mdx

Adding TeamsFx to the Overview page

---

packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts

Closes #1641 
- Bugfix
The aria 'input' role is an abstract role and may not be recognized. The input box represents a searchbox and therefore the searchbox' role is better suited.
Before fix: 
After fix:

Update aria-role to 'searchbox'

---

index.html
packages/mgt-components/src/components/mgt-login/mgt-login.ts
packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.scss
packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts
packages/mgt-components/src/components/mgt-person-card/sections/mgt-person-card-organization/mgt-person-card-organization.scss
packages/mgt-components/src/components/mgt-person/mgt-person.scss
packages/mgt-components/src/components/mgt-person/mgt-person.theme.scss
packages/mgt-components/src/components/mgt-person/mgt-person.ts
packages/mgt-components/src/graph/types.ts
packages/mgt-components/src/styles/shared-sass-variables.scss
stories/components/fileList/fileList.properties.js
stories/components/person/person.js
stories/components/person/person.properties.js
stories/components/person/person.templating.js
stories/components/personCard/personCard.a.js

Closes #1607
Feature
Update People component to latest fluent UI design. Similar to https://github.com/microsoftgraph/microsoft-graph-toolkit/pull/1619
This PR contains changes is main. May contain breaking changes due to rebasing.

[person]: Update person component to latest Fluent UI design

---

package.json
packages/mgt-element/src/components/baseComponent.ts

Closes #1817
- Refactoring (no functional changes, no api changes) 
Updates the common TypeScript version being used.

chore: update to typescript v4

---

packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts

Closes #1725  
- Bugfix
Allows showing the people supplied in the dropdown as well as search them
I raised an internal discussion to discuss how to add `person?.userPrincipalName` filter. Will be updated in due time.

fix: Allow display and searching of people supplied in attributes

---

package.json
packages/providers/mgt-electron-provider/package.json

Closes #1844  
Locked the `responselike` package to version 2.0.0.

update: Lock responselike package resolutions to v2.0.0

---

.storybook/manager-head.html
.storybook/preview-body.html
packages/mgt-components/src/components/mgt-file-list/mgt-file-upload/mgt-file-upload.ts
packages/mgt-components/src/components/mgt-login/mgt-login.scss
packages/mgt-components/src/components/mgt-person/mgt-person.scss
packages/mgt-components/src/components/mgt-person/mgt-person.ts

Closes #1538, #1583 and #1567 
Bugfix
- Adds keyboard focus on canvas and overview copy buttons on storybook
- Fixes person focus visibility for Agenda and people component
- Adds keyboard focus to login sign-in button
- Adds file input label to file list upload

update: add keyboard focus on storybook canvas and overview copy buttons

---

packages/providers/mgt-teamsfx-provider/package.json

[teamsfx-provider] Update teamsfx peer dependency to 2.x.x

---

packages/mgt-components/src/graph/graph.user.ts

Closes #1853  
- Bugfix
Use optional chaining to read null properties in User.

fix: Use optional chaining for null user object

---

.storybook/addons/codeEditorAddon/editor.js
packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.scss
packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts

Closes #1509  
- Bugfix
Fixes the focusing action on the people-picker component using tabs and clicking in the input. This should load the default people and show the flyout. In case people are not available, show the not found message on the flyout.
This fixes RTL issues when rendering people in the people picker. The X button was appearing on top of the avatar. This fix ensures that it is rendered to the left in RTL direction.
When you select people for copy/cut actions, the X button would appear on the right on top of the image. This fix ensures that the X button is rendered correctly on the left and extra margins are removed.
Fixes a bug that threw an error on editor loading in the story book. `this.editor` doesn't have the `removeListener` method so the `.dispose()` method is used …

fix: People picker RTL renders, focus and storybook loading errors

---

SECURITY.md
packages/mgt-components/README.md
packages/mgt-element/README.md
packages/mgt-react/readme.md
packages/mgt-spfx/config/package-solution.json
packages/mgt/README.md
packages/providers/mgt-electron-provider/README.md
packages/providers/mgt-msal-provider/README.md
packages/providers/mgt-msal-provider/src/MsalProvider.ts
packages/providers/mgt-msal2-provider/README.md
packages/providers/mgt-proxy-provider/README.md
packages/providers/mgt-sharepoint-provider/README.md
packages/providers/mgt-teams-msal2-provider/README.md
packages/providers/mgt-teams-provider/README.md
packages/providers/mgt-teamsfx-provider/README.md
readme.md
samples/angular-app/README.md
samples/angular-app/src/app/nav-bar/nav-bar.component.html
samples/electron-app/README.md
samples/msal2provider-asp-net-core-sso/Pages/Index.cshtml
samples/msal2provider-asp-net-core-sso/wwwroot/css/site.css
samples/proxy-provider-asp-net-core/README.md
samples/proxy-provider-asp-net-mvc/README.md
samples/proxy-provider-node/README.md
samples/sp-webpart/README.md
samples/teams-sso-node/readme.md
samples/teams-tab/readme.md
specs/mgt-picker.md
stories/feedback.stories.mdx
stories/overview.stories.mdx

Closes #1873  
Changed the links from https://docs.microsoft.com to https://learn.microsoft.com. I updated the links to remove hard-coded locale codes.
The links in https://aka.ms/mgt/docs don't need this update. They are all relative links as recommended.

update: links to learn.microsoft.com

---

packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts

Closes #1868 
Bugfix
The keydown method has been extended to check if the key pressed is 'Enter' before Person deletion is done

Fix: People picker deletion

---

.github/workflows/pr-storybook.yml

ci: remove explict token from gh pages deploy

---

.storybook/manager-head.html
packages/mgt-components/src/components/mgt-people/mgt-people.ts
stories/components/login/login.stories.js

Closes #1554  
Bugfix
Removes focus on people overflow as it's not currently interactive.
Removes go to profile button on login story, and replaces with My profile button.

update: remove overflow focus on people component

---

packages/mgt-components/src/components/mgt-agenda/mgt-agenda.ts

Removes assumption that local time is aligned with the calendar time. Closes #1886

---

packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts

Closes #1889  
- Bugfix 
- Removes the adding of people action on the Tab key.
- Sets the dropdown to show when you focus on the input.

update: show the dropdown when you focus on the people picker with tab key

---

packages/mgt-components/src/components/mgt-people/mgt-people.ts

Removes null people from the result when no fallback details specified. Closes #1885

---

packages/mgt-components/src/components/mgt-person/mgt-person.ts
packages/mgt-components/src/components/mgt-person/strings.ts
packages/mgt-components/src/utils/FluentComponents.ts
packages/mgt-spfx/src/index.ts
packages/mgt-spfx/src/libraries/mgt/MgtLibrary.ts
packages/mgt-spfx/src/libraries/mgt/loc/en-us.js
packages/providers/mgt-msal2-provider/src/Msal2Provider.ts
packages/providers/mgt-msal2-provider/src/index.ts
packages/providers/mgt-teamsfx-provider/src/index.ts

Closes #1907  
- Bugfix
- Changed the title text to have a prefix if the person details have an image or the avatar type is initials.
- Changed the alt text to have the prefix "photo for".
- Refactored portions of the code that had unused variables and set `hasInitials` variable for repeated code.
- Set the license header on all files.

fix: update the text announced for person image, initials and email address

---

.vscode/settings.json
package.json
packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
packages/mgt-components/src/graph/graph.presence.ts
packages/mgt-react/src/generated/react.ts

Closes #1955
- Bugfix
Fixes TypeScript compilation issues that are now occurring during CI builds but not on local builds

fix: correct compilation errors for CI build

---

packages/providers/mgt-teamsfx-provider/README.md
packages/providers/mgt-teamsfx-provider/src/TeamsFxProvider.ts

Closes #1961 
Docs PR: https://github.com/microsoftgraph/microsoft-graph-docs/pull/19263

[teamsfx-provider] Allow use TeamsUserCredential to construct instance

---

.storybook/manager-head.html

Closes #1544  
- Bugfix
This search-field raises accessibility issues from rendering results after a search. Fixing the issues is complex. Since the component is hardly used, we remove it to mitigate the accessibility issues.

fix: remove the search field from the playground

---

packages/mgt-components/src/components/mgt-file-list/mgt-file-list.ts
stories/components/fileList/fileList.properties.js

Closes #1707  
Bugfix
Check for page-size when filtering by file extensions

fix: check for page-size when filtering by extensions in FileList

---

.github/workflows/pr-reporting.yml

Experiment to see how external PRs behave with test reporting.

[CI] Testing PR with test results from external fork

---

specs/mgt-picker.md

Removed the selected-item template

---

.storybook/fix-title.js
package.json

Closes #1779
- Bugfix 
Adds code to re-write the generated html for storybook to correct the title tag and inject some meta descripttions

bug: fix html title for mgt.dev

---

packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.scss

Closes #2030  
- Bugfix
- Sets the search icon to be on the same level with the input field.
- Fixes layout issues when a person pill is selected and they overlap when they are stacked.

fix: set the search icon to be on the same level with the input field

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Closes #2050 
Adds a devcontainer

chore: add a base devcontainer

---

packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts

Closes #2007
- Bugfix 
refactors the search behavior triggered the keyup event to be triggered on the input event of the text box instead.

bug: fix voice input for people picker

---

packages/mgt-components/src/components/mgt-person/mgt-person.scss
stories/components/person/person.properties.js

- added story to demonstrate
- fixes: #2070
Closes #2070 
- Bugfix
- [ x Added appropriate [documentation](https://github.com/microsoftgraph/microsoft-graph-toolkit/wiki/Documentation). Docs PR:

mgt-person: fix avatar scaling issue

---

packages/mgt-components/src/components/mgt-people/mgt-people.scss
packages/mgt-components/src/components/mgt-people/mgt-people.ts
stories/components/people/people.styles.js

Closes #2077 
- Feature
Update the people component to fluent UI theming.
Updated the mgt tokens.

feat: use fluent ui to theme the people component

---

packages/mgt-components/src/components/mgt-agenda/mgt-agenda.scss
packages/mgt-components/src/components/mgt-agenda/mgt-agenda.theme.scss
stories/components/agenda/agenda.style.js

Closes #2079 
Feature
Adds theming tokens to mgt-agenda
Builds on #2136 person-card theme

feat: use fluentui tokens to theme mgt-agenda

---

packages/mgt-components/package.json

this makes it easier to build when switching between branches that different sets of components
Closes #2177 
- Bugfix

chore: remove *-css.ts files during clean

---

packages/mgt-components/src/index.ts
stories/components/theme-toggle/themeToggle.js

Closes #2198  
- Feature
- Export the `applyTheme` function to theme a component without the theme toggle component.
- Add a story demonstrating how to theme a component without the theme toggle component.

feat: allow programmatically theming a component without the theme-toggle component

---

readme.md

removed web components link and badge as it is broken

chore: readme maintenance

---

.storybook/addons/signInAddon/signInAddon.js
artifacts/install.ps1
auth.html
index.html
packages/mgt-components/README.md
packages/mgt-element/README.md
packages/mgt/README.md
packages/providers/mgt-msal-provider/src/MsalProvider.ts
packages/providers/mgt-msal-provider/src/mgt-msal-provider.ts
packages/providers/mgt-teams-msal2-provider/README.md
packages/providers/mgt-teams-msal2-provider/src/TeamsMsal2Provider.ts
packages/providers/mgt-teams-msal2-provider/src/mgt-teams-msal2-provider.ts
packages/providers/mgt-teams-provider/README.md
packages/providers/mgt-teams-provider/src/TeamsProvider.ts
packages/providers/mgt-teams-provider/src/mgt-teams-provider.ts
samples/examples/login-redirect-nopopup.html
samples/examples/onboarding/index.html
samples/react-app/package.json
samples/react-app/src/index.tsx
samples/teams-tab/index.html
specs/mgt-login.md

feat: mark Teams, TeamsMsal2 and Msal providers as deprecated in v2.x.x

---

.github/policies/branch-protection.yml

chore: branch protection rules

---

packages/mgt-react/package.json

Closes #2063 
- Bugfix
Adds peer dependencies to mgt-react for React v17

fix: react peer dependencies

---

.github/workflows/codeql-analysis.yml

Closes #2222 
Updates version of CodeQL actions being used in workflow
CI change only

chore: update codeql actions to v2

---

package.json
packages/mgt-components/package.json
packages/mgt-components/src/components/mgt-person/mgt-person.tests.ts
packages/mgt-element/package.json
packages/mgt-element/src/utils/version.ts
packages/providers/mgt-electron-provider/package.json
packages/providers/mgt-msal-provider/package.json
packages/providers/mgt-msal2-provider/package.json
packages/providers/mgt-teams-msal2-provider/package.json
packages/providers/mgt-teams-provider/package.json

fix: pin graph client version

---

.github/workflows/push-preview-release.yml
package.json

Sets up the version number and packaging automation to use the rc segment in the version number

chore: set up for rc1 release

---

packages/mgt-components/src/components/preview/mgt-search-results/mgt-search-results.ts
packages/mgt-element/src/utils/version.ts
samples/react-admin-app/src/pages/Search/AllResults.tsx
samples/react-admin-app/src/pages/Search/ExternalItems.tsx
samples/react-admin-app/src/pages/Search/Interleaving.tsx
samples/react-admin-app/src/pages/Search/PeopleResults.tsx
stories/components/preview/searchBox/searchBox.a.js

fix: execute beta queries and eliminate re-renders

---

packages/mgt-components/src/components/mgt-person/mgt-person.scss

Closes #2428 
- Bugfix 
Align the person details for a logged in user to the right in `mgt-login`

fix: right align the person details in mgt-login component

---

index.html
packages/mgt-components/src/components/mgt-tasks/mgt-tasks.ts
packages/mgt-components/src/components/sub-components/mgt-dot-options/mgt-dot-options.scss
packages/mgt-components/src/components/sub-components/mgt-dot-options/mgt-dot-options.ts
stories/components/tasks/tasks.stories.js

Closes #2474  
- Bugfix
fixes filtering logic for displaying tasks loaded from todo

fix: ensure todo tasks are rendered in mgt-tasks

---

samples/proxy-provider-node/auth.ts
samples/proxy-provider-node/client/index.html
samples/proxy-provider-node/package.json
samples/proxy-provider-node/proxy.ts
samples/proxy-provider-node/yarn.lock

Closes #2466 
- Bugfix 
fixes for new version of typescript
fixes nodemon to dev dependency
updates index.html to use v3 (at release)

fix: proxy sample node

---

packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
stories/components/teamsChannelPicker/teamsChannelPicker.style.js

Closes #2453 
- Bugfix
Remove unused tokens and ensured all the other tokens had an actual effect when changed.
Updated the styling story with the right set of properties.

fix: CSS tokens for `mgt-teams-channel-picker`

---

packages/mgt-components/src/components/mgt-person-card/mgt-person-card.scss

fix: person-card hover icons alignment

---

stories/components/taxonomyPicker/taxonomyPicker.properties.js
stories/components/taxonomyPicker/taxonomyPicker.templating.js

Closes #2535  
- Bugfix 
removes commented out code and corrects component name for a story

correct the component name in storybook

---

readme.md

Updating README with latest version

---

package.json
yarn.lock

fix: storybook deployment

---

package.json
readme.md
yarn.lock

Storybook + documentation update

chore: fix storybook and update readme

---

scripts/uploadSpfxSolution.js

Closes #2551 
- Bugfix 
fixes some logical problems in the script to upload the sppkg after publishing to npm

fix: correct sppkg upload script

---

.github/policies/microsoft-graph-toolkit-branch-protection.yml

Closes #2574  
Build or CI related changes 
Apply policy to more branches to require CI checks

chore: update branch protection policy

---

package.json
yarn.lock

chore: remove storybook-deployer dependency

---

stories/components/login/login.styles.js

Closes # 
- Bugfix
Adds a login class to mgt-login styling story

chore: add a login class to mgt-login styling story

---

packages/mgt-components/src/components/mgt-tasks/mgt-tasks.scss

Closes #2498  
Bugfix
Add font-family to mgt-tasks

fix: add font family to mgt-tasks to fix unstyled font

---

stories/components/peoplePicker/peoplePicker.style.js

Closes #2601 
Bugfix
Adds in a people-picker class to fix customization in people-picker component

fix: add people-picker class to people-picker

---

CHANGELOG.md

Brings changelog up to v3 release

chore: update change log with v3 and v3 rc changes

---

scripts/uploadSpfxSolution.js

Closes #2616  
adds v prefix version to ensure that existing releases are found

ci: update spfx uploader script

---

packages/mgt-components/src/graph/graph.user.ts

fix: use correct scope for group member resolution.

---

.github/workflows/pr-chat.yml

ci: add workflow to deploy mgt-chat sample app

---

packages/providers/mgt-msal2-provider/src/Msal2Provider.ts

Closes # 
- Bugfix 
adds an awaited initialize check to the Msal2Provider initialize method
This is required in MSAL v3
This change should allow Anglar16 developers to use the msal-angular v3 package to create and pass in a public client application. 
It's compatible with msal-browser v2 as the initialize method exists with the same signature on the PublicClientApplication class in that version.
When merged we will need to do additional testing with an Angular16 project to detect any other issues which may require us publishing an `@microsoft/mgt-msal3-provider` package for clean version separation and support.

fix: ensure msal public client application is initialized

---

.github/workflows/pr-chat.yml

ci: use | instead of / as separator for sed commands

---

packages/mgt-spfx/config/package-solution.json

Update solution name to v3

---

stories/components/person/person.templating.stories.js

Closes #2743 
- Bugfix
Add a query for retemplatingMetadata story in `mgt-person`.

chore: add query for retemplateMetadata story on mgt-person

---

packages/mgt-components/src/components/mgt-person/mgt-person.tests.ts
packages/mgt-components/src/components/mgt-person/mgt-person.ts
stories/components/person/person.properties.stories.js

Closes #2763 
- Bugfix 
Adds tests and correct checks to ensure that we don't attempt to read into a nullish or empty string value.

fix: initials rendering in mgt-person

---

packages/mgt-chat/src/components/Chat/Chat.tsx

Closes #2709 
- Bugfix
- Change the person card interaction mode to `hover` on rendered sender avatars.
-

fix: show the person card of a sender when you hover on the avatar

---

packages/mgt-chat/package.json

Closes #2775  
- Bugfix 
Ensure that both src and dist folders are included in the published package sent to NPM

fix: update files included in mgt-chat package when publishing

---

packages/mgt-components/src/components/mgt-person/mgt-person.ts
stories/components/person/person.properties.stories.js

Closes #2720  
Bugfix
Fixes the bug where fallback-details appear to override person-query

fix:  remove the fallback-details override of person-query

---

.github/workflows/codeql-analysis.yml
.github/workflows/next.yml
.github/workflows/pr-clean-deployments.yml
.github/workflows/pr-reporting.yml
.github/workflows/pr-storybook.yml
.github/workflows/pr.yml
.github/workflows/push-preview-release.yml
.github/workflows/push-release.yml
.github/workflows/push.yml
.github/workflows/run-release-please.yml
.github/workflows/storybook.yml

chore: fix node actions version

---

packages/mgt-components/src/graph/graph.people.ts
stories/components/peoplePicker/peoplePicker.properties.stories.js

fix: remove double filtering in mgt-people-picker people filters

---

packages/mgt-chat/package.json
yarn.lock

fix: mgt-chat now has peer deps including react 18

---

packages/mgt-chat/src/index.ts
packages/mgt-chat/src/statefulClient/chatOperationScopes.tests.ts
packages/mgt-chat/src/statefulClient/chatOperationScopes.ts
packages/mgt-chat/src/statefulClient/graph.chat.ts
packages/mgt/src/index.ts
samples/react-chat/src/App.tsx

fix: ensure that allChatScopes provides all scopes needed

---

.storybook/addons/codeEditorAddon/codeAddon.js
.storybook/manager.js

Closes #2850  
- Feature
enables users to authenticate to the storybook site
ensures that components are registered for use in stories
 

feat: enable user sign-in for storybook

---

.github/workflows/pr-chat.yml
packages/mgt-components/src/components/mgt-person/mgt-person.tests.ts

fixes deployment issue with heap size for node

chore: bump heap size for chat test app deployment

---

packages/mgt-chat/src/components/Chat/Chat.tsx

Closes #2858 
Bugfix
add presence to avatars in the chat thread

fix: chat avatar presence display

---

.github/workflows/pr-clean-deployments.yml

Closes #2856  
moves workflow to use one job with conditional steps

chore: re-work cleanup pipeline

---

packages/mgt-chat/src/components/Chat/Chat.tsx
packages/mgt-chat/src/utils/mentions.tsx

Closes #2806  
- Bugfix
Set the color of other mentions to blue.

fix: differentiate between me mentions and other user mentions

---

packages/mgt-element/src/mock/MockMiddleware.ts

fix: update the sandbox fallback url

---

stories/components/picker/picker.html.stories.js

Closes #2960  
Adds a story for key-name nested values in mgt-picker

docs: add story for picker nested values

---

.github/workflows/pr-reporting.yml

Closes #3006  
contents: read - allows reading commits of the pr
checks: write - reports the status of the job on the pr
id-token: write - dorny/test-reporter@v1 uses the token for OIDC, this allows fetching it.
- Current PR reporting will ALWAYS fails as this PR will run the old workflow steps.
- Merge to `main` and then check the actions tab to ensure that this change passes the workflow https://github.com/microsoftgraph/microsoft-graph-toolkit/actions
-

chore: Update the permissions for PR reporting.

---

stories/samples/general.stories.js

Closes #2309  
Bugfix
Make clear-cache button adopt to theming

fix: make clear cache button adopt theming

---

packages/mgt-components/src/components/mgt-todo/mgt-todo.ts

Closes #2304  
- Bugfix
focus on the input when you cancel adding a todo

fix: focus on the input when you cancel adding a todo

---

packages/providers/mgt-msal2-provider/src/Msal2Provider.ts

Closes #3016 
- Bugfix
adds complete null checks to early exit conditons to avoid trying to access properties on a nullish object.

fix: msal setActiveAccount error

---

packages/mgt-components/src/components/mgt-todo/mgt-todo.ts

fix: correct completion of todo items

---

stories/components/person/person.docs.stories.js
stories/components/person/person.properties.stories.js

docs: update view usages

---

packages/mgt-chat/src/components/Chat/Chat.tsx

Closes # 3062
Code style update (formatting)

[MGT-CHAT] Fix style so chatbox is always at bottom

---

packages/mgt-chat/src/utils/mentions.tsx

Closes #3101 
- Bugfix
Adds a key to mentions to prevent a react error

fix: add key to mentions

---

packages/mgt-components/src/components/mgt-search-results/mgt-search-results.scss

Closes #3113  
- Bugfix 
uses the common variable for --color

fix: theme colors for search results

---

packages/mgt-components/src/components/mgt-search-results/mgt-search-results.scss

Closes #3152 
Bugfix 
Added color variable for date and summary for dark mode for search-results react component

added color variable for date and summary

---

stories/components/personCard/personCard.style.stories.js

fix(a11y): correct person-card contact icons hover style accessibility contrast

---

stories/components/fileList/fileList.style.stories.js

fix(a11y): correct file upload button and file line-1 color contrast in mgt-file-list

---

stories/components/fileList/fileList.properties.stories.js

fix(a11y): alert files reloaded on mgt-file-list

---

stories/components/peoplePicker/peoplePicker.properties.stories.js

fix: keyboard focus behavior on modal interactions in mgt-people-picker story

---

packages/mgt-components/src/components/mgt-file/mgt-file.ts

fix(a11y): use descriptive alt text for file icon in mgt-file

---

packages/mgt-components/src/components/mgt-planner/mgt-planner.ts

fix: mgt-planner task deletion on keyboard interaction

---

packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts

fix: display only available person-card contact icons on mgt-person-card

---

release-please-config.json

Closes #3245  
Fix failing release-please build by listing individual file paths in the release please configuration

chore: list individual file paths to be updated with version on release

---

packages/mgt-components/src/components/mgt-login/mgt-login.ts

Closes #3249
- Bugfix
Fixes issue in login component when flyout stops working after relogin. Also refactored logout method order of getActiveAccount call.

fix: show login component flyout on after login

---

packages/mgt-components/src/graph/graph.user.ts

fix: remove space in findUsers query

---

packages/mgt-components/src/graph/graph.user.ts

Closes #3258 
Closes #3170 
- Bugfix
Add `ConsistencyLevel: eventual` and `$count` query parameter to query string.

fix: use advanced queries capabilities when people-picker has input and group-id

---

packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts

fix: remove picker focus when using selectUsersById

---

packages/mgt-components/src/components/mgt-file-list/mgt-file-list.theme.scss
packages/mgt-components/src/components/mgt-file-list/mgt-file-upload/mgt-file-upload.scss

fix: correct mgt-file-upload dialog content z-index

---

.github/workflows/pr.yml

chore: update upload and download artifact actions

---

.github/dependabot.yml

chore: reduce frequency of dependabot updates

---

packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
packages/mgt-components/src/components/mgt-teams-channel-picker/strings.ts

Closes #3383 
Closes #3380  
Bugfix
On the provided links, with narrator open, test that the picker buttons are announced correctly and that keyboard focus does not appear twice on the up and down chevrons.

fix(a11y): improve keyboard accessibility in mgt-teams-channel-picker

---

packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts

fix: tree item collapse in mgt-teams-channel-picker
