microsoftgraph/microsoft-graph-toolkit

- src/components/mgt-tasks/task-sources.ts
Bugfix
Fixed unintentionally sending dueDateTime on new ToDo tasks, which resulted in new tasks having a due date of January 1st, 1601.
> [bugfix] Fixed unintentionally sending dueDateTime on new ToDo Tasks

- samples/examples/templates.html
- src/components/templateHelper.ts
- src/components/templatedComponent.ts
- Feature
This PR adds support for converters in our templates. Ex:
```html
<mgt-agenda id="myDay">
<template data-type="event">
<div>
<div>{{ event.subject }}</div> 
<div>{{{ myConverter(event.subject }}}</div> 
</div>
</template>
</mgt-agenda>
<script>
let agenda = document.getElementById('myDay');
agenda.templateConverters.myConverter = str => str.toUpperCase();
</script>
```
> Added support for template converters

- src/components/mgt-person/mgt-person.scss
- Bugfix
There is a difference in size between a loaded person and when no person is loaded in the mgt-person component. This PR makes sure both avatars are the same size
> [mgt-person] Fixed avatar size when no person is loaded

- src/components/mgt-people-picker/mgt-people-picker.ts
Closes #138 
Bugfix
Updating the logic for mousetracking behavior from an eventlistener to onblur and focus. This is a fix found from the vernier project.
> [people-picker] updating the mousetracking behavior 

- src/components/mgt-people-picker/mgt-people-picker.ts
Closes # N/A
Bugfix
Feature 
Since the replacement of map to repeat for performance in the rendering of people, showmax was not implemented. This reimplements the feature.
> [people-picker] reimplement showMax on people-picker

- src/components/mgt-agenda/mgt-agenda.ts
Closes #146 
Bugfix
Creating the `end` by passing `start.getTime()` to the constructor makes a copy of `start`. You can then add days to it as needed.
> Fixed end date calculation for calendarview query

- samples/examples/person-card.html
- src/components/mgt-person-card/mgt-person-card.ts
- Feature 
This PR adds the `inherit-details` attribute to ѝmgt-person-cardѝ. When this attribute is set, the person card will walk the parent tree until it finds an `mgt-person` component and use the same `person-details` and `person-image`. This is useful when the `mgt-person-card` component is used in aн `mgt-person` template. 
Before this attribute, the developer would have to use template binding:
```html
<mgt-person person-query="me" show-name show-email person-card="hover">
<template data-type="person-card">
<mgt-person-card person-details="{{ person }}" person-image="{{ personImage }}"></mgt-person-card>
</template>
</mgt-person>
```
With `inherit-details`, the developer just needs to set the attribute:
```html
<mgt-person person-query="me" show-name show-email …
```
> [mgt-person-card] added inherit-details attribute 

- src/components/templatedComponent.ts
- Feature
This PR fixes a bug where an exception was being thrown when a template is empty. Ex:
```html
<mgt-person-card>
<template data-type="additional-details"></template>
</mgt-person-card>
```
Empty template can be useful when the developer wants to add the content in code behind (in js).
> Fixed exception when empty template is used in a component

- src/components/mgt-person/mgt-person.scss
Closes #166 
Bugfix
added color var to the mgt-person component
OS: Mac OS Majave Version 10.14.6
Browser: Chrome Version 77.0.3865.90
Framework: none
Context: Web
Version: 1.0.0
> Issue #166: added color css var to mgt-person comp

- src/components/mgt-tasks/mgt-tasks.ts
- src/components/mgt-tasks/task-sources.ts
Closes #152
- Bugfix
This PR fixes an issue where the the creation of tasks was not working when using a negative timezone (ie UTC - 3)
> Fixed timezone issue in tasks component

- src/components/mgt-person/mgt-person.scss
Closes #169 
- Bugfix
People with no image in and just initials were misaligned with other users who did have an image. The change I made was to make the `mgt-person` container `display: flex` instead of inline-block. This allows the default container to take up as much room as it needs to without using any extra space explicitly.
> display flex brings the initials up with the images

- src/components/mgt-person/mgt-person.ts
Closes #167
Hello,
This is a minor fix aimed at addressing #167.
The change is simple enough. However, I dug a little deeper to verify the change and I think there's a separate issue with the component template rendering pipeline which causes custom template definitions to not work.
Specifically, something feels a little off to me with this block:
https://github.com/microsoftgraph/microsoft-graph-toolkit/blob/3f7814c74f202b6492a64744bed7c73579c62c43/src/components/templatedComponent.ts#L91-L97
For the `Person` component with a custom template, I observed a `<div slot="default" data-generated="template">` being appended on the initial render (i.e. no person data yet). Once person data becomes available, the above block of code appears to short-circuit the component re-render. This means …
> Include image data for person component context

- src/components/mgt-agenda/mgt-agenda.ts
- Feature
Adding an `eventClick` event when a user clicks or taps on an event. 
Usage:
```js
let agenda = document.querySelector('mgt-agenda');
agenda.addEventListener('eventClick', e => {
console.log(e.detail.event.subject);
});
```
> [Agenda] Adding eventClick event

- src/components/templatedComponent.ts
- src/utils/Utils.ts
- tests/Utils.tests.tsx
Hello,
This is a fix aimed at addressing #165.
The gist of the changes follow from some discussion in both #165 and #177.
To recap:
* The primary problem discovered was that any rendered slot element didn't re-render itself when its context data was updated
* The proposed changes will keep track of any context data previously used to render a slot and will effectively perform a re-render if the data has changed
* The change detection is done by a rather crude function that _should_ be sufficient for testing deep equality between objects
The test suite appears to be broken at this time. Specifically, the only test file I could find was `MsalProvider.tests.tsx`, and the TS compiler isn't happy about it. I've still added some tests for the `equals()` function used to do context diffing. They …
> Fix slot re-render for context updates

- src/components/providers/mgt-msal-provider.ts
- src/components/providers/mgt-proxy-provider.ts
- src/components/providers/providers.ts
- src/providers/ProxyProvider.ts
- src/providers/providers.ts
- src/utils/CustomHeaderMiddleware.ts
- src/utils/ProxyGraph.ts
- src/utils/SdkVersionMiddleware.ts
Closes # 
- Feature
Adds a proxy provider, so users can use their own server side auth with the graph and still use mgt without needing to signing in twice.
> Added Proxy provider

- src/components/mgt-person-card/mgt-person-card.ts
- src/components/templateHelper.ts
- Bugfix
This pr fixes an issue where a `data-for` loop is used in a template and items are rendered out of order.
This pr also adds the personDetails and personImage in the context of the templates in the person-card component
> Fix for templates not rendering children in the right order

- samples/examples/person-card-get.html
- src/components/mgt-person-card/mgt-person-card.ts
- src/components/templateHelper.ts
- Feature
This PR introduces new properties in the template context when binding:
* $index is added to the context of each item being looped with data-for. This is useful when a developer needs to know the index of an item being rendered
* $parent is added to the context of a template when rendered inside of another template. This is useful when the developer needs to use context from a parent template
* when looping, all context is preserved. Before only the item being looped was available
This PR also fixes an issue where person-card image was not passed as context to a template.
> Templates - introducing $index and $parent

- src/components/mgt-person/mgt-person.scss
- src/components/mgt-person/mgt-person.ts
Closes #204 
Bugfix
- Removed the `<img />` tag that doesn't do anything when only initials are displayed.
- Top align `.root`.
> Fixed person comp alignment issue.

- src/components/mgt-people/mgt-people.scss
- src/components/mgt-people/mgt-people.ts
Closes #198 
Bugfix 
Adds overflow class to show-max conditionally rendered mgt-people. Both `align-items` in the parent, and `vertical-align` css properties are necessary for handling mgt-people standalone + mgt-people rendered in mgt-agenda.
> [mgt-people] setting overflow to align with peoplelist vertically

- src/components/mgt-tasks/mgt-tasks.ts
- Feature 
This PR is adding the `taskFilter` property to the `mgt-tasks` component to allow additional filtering of tasks. The taskFilter must be a function that accepts a task object as a parameter and returns true if the task should be rendered, false otherwise. The task object can be a planner task or an outlook (todo) task depending on the source the developer is using.
For example, I developer could choose to only render tasks in a specific category by providing the following filter:
```js
let taskView = document.querySelector('mgt-tasks');
taskView.taskFilter = task => task.appliedCategories.category3;
```
> Adding taskFilter property to mgt-tasks

- src/components/mgt-person/mgt-person.ts
Closes #203 
Bugfix
adding condition to return if user clicks inside the card itself.
> [person] updating mouseEnter to not reset if click inside of the card

- index.html
- src/components/baseComponent.ts
- src/components/mgt-person/mgt-person.scss
- src/components/mgt-person/mgt-person.ts
- src/components/mgt-tasks/mgt-tasks.scss
- src/components/mgt-tasks/mgt-tasks.ts
- src/components/sub-components/mgt-flyout/mgt-flyout.scss
- src/components/sub-components/mgt-flyout/mgt-flyout.ts
Closes #202 
- Bugfix
This PR introduces a new internal component for rendering flyouts (`mgt-flyout`) and replaces all code where we render a flyout (person-card in person, and people-picker in tasks). The new component helps to avoid re-implementing flyouts for every component that needs it and ensures all flyouts behave the same. 
mgt-flyout measures the content to render and ensures the flyout is fully visible on screen when possible.
> Fixed issue where flyouts render outside of window bounds

- src/components/mgt-login/mgt-login.ts
- src/components/mgt-person/mgt-person.scss
- src/components/mgt-person/mgt-person.ts
Closes #168 
Bugfix
Two things:
1. This was meant originally to fix the touch issue described in the issue above. After changes were made to the card hide functionality the issue no longer seemed present. 
However,
The person-card if in expanded view, touch events will not hide the person-card. The user previously would have to close only by touching the person icon again. The new functionality will hide the person-card if the user `touch` anywhere else *but* the card. 
2. Refactors `mgt-login`  click event was originally handled in the firstUpdated cycle. Now is attached and detached properly.
> Person-card touch to hide issue + login refactor (window event)

- src/components/mgt-people-picker/mgt-people-picker.scss
Closes #231 
Bugfix
All components of people-picker use the same font.
> [people-picker] font via inheritance of css variable fixing osx issue

- index.html
- src/mock/mgt-mock-provider.ts
Closes #189 
- Feature
Adding signed-out boolean property to mock provider tag in order to pass into construction of MockProvider.
This can be useful for testing or seeing the entire user experience of both disconnected and connected from the graph.
I didn't see any existing docs for mgt-mock-provider, nor did I write any.
> Adding signed-out attribute to mgt-mock-provider (#189)

- .storybook/signInAddon.js
- Bugfix
When story is loaded inside of iframe, provider will be set as mock provider.
- [X ] Project builds (`npm run build`) and changes have been tested in supported browsers (including IE11)
- [ X] All public classes and methods have been documented
- [ X] Added appropriate [documentation](https://github.com/microsoftgraph/microsoft-graph-docs/tree/master/concepts/toolkit)
- [X ] License header has been added to all new source files (`npm run setLicense`)
- [X ] Contains **NO** breaking changes
> Add default provider when addons are not loaded

- src/BaseGraph.ts
- src/Graph.ts
- src/components/mgt-agenda/mgt-agenda.ts
- src/components/mgt-get/mgt-get.ts
- src/components/mgt-login/mgt-login.ts
- src/mock/MockGraph.ts
- src/utils/Batch.ts
- src/utils/ComponentMiddlewareOptions.ts
- src/utils/SdkVersionMiddleware.ts
- Bugfix
This PR fixes an issue where a new graph client object was instantiated for each call made by a component. This caused issues with throttling since there is not one client to keep track of all requests. 
With these changes, the `Graph.forComponent` method still returns a new instance of Graph, but the graph client instance stays the same. 
To allow the header of each request to include the name of the component, a new `BaseGraph.api()` method was created that should be used internaly instead of `client.api()`. This method acts the same as `client.api()` with the exception that it injects the name of the component in the request by using a middleware option for each request.
In addition to the above change, this PR also updates the MockProvider to automatically escape the request …
> Updated BaseGraph to always use the same client instance

- src/components/mgt-people-picker/mgt-people-picker.ts
- src/components/mgt-people/mgt-people.ts
- src/graph/graph.user.ts
Closes #310 
- Bugfix
This PR fixes #310 
As part of this:
* Ensured the current list of people get updated minimally by not fetching users already loaded in people
* Ensured constantly updating user-ids attribute keeps the list in order and elements are loaded properly
* All users are now also loaded using the batch API in one call
While working on this issue, I discovered and fixed an issue affecting how mgt-people-picker and mgt-people work together.
This code:
```js
picker.addEventListener('selectionChanged', e => {
people.people = picker.selectedPeople;
});
```
was not working as expected because when selecting additional people in people picker, a person was appended to the selectedPeople array. Since the reference of the array never changed, the people component doesn't know the …
> fixed issue where mgt-people was not updating when user-ids changed

- .storybook/addons/codeEditorAddon/codeAddon.js
- .storybook/preview-body.html
Closes #308 
- Bugfix 
Add wrapper to have preview area own its margin
> Fix Storybook iframe embed with extra scroll

- src/components/mgt-people/mgt-people.ts
Contributes to #267 
- Feature
New render methods for `mgt-people`:
- `render()`
- `renderLoading()` - Render the loading state.
- `renderNoData()` - Render the no data state.
- `renderPeople()` - Render the list of people using `renderPerson` and calls `renderOverflow` if necessary.
- `renderPerson(person)` - Render an individual person.
- `renderOverflow()` - Render the overflow content to represent any extra people, beyond the max.
Supported templates:
- `loading` - (*NEW*) Used while the component is loading state
- `no-data`
- `default`
- `person`
- `overflow`
All of the methods operate using public/protected props (except `renderPerson`) so I decided not to pass the values around, but I could be convinced otherwise. 
Docs:
https://github.com/microsoftgraph/microsoft-graph-docs/pull/7 …
> Restructured render methods in mgt-people

- src/components/mgt-person-card/mgt-person-card.scss
Closes #323 
- Bugfix
This fixes the issue where `mgt-person-card` displays the incorrect font when used as a standalone component. 
Test with the following code:
```
<mgt-person person-query="me"></mgt-person>
<mgt-person-card></mgt-person-card>
<script>
const person = document.querySelector('mgt-person');
const personCard = document.querySelector('mgt-person-card');
person.addEventListener('loadingCompleted', () => {
personCard.personDetails = person.personDetails;
});
</script>
```
> Fix person card default font family

- src/components/baseComponent.ts
- src/components/mgt-agenda/mgt-agenda.graph.ts
- src/components/mgt-agenda/mgt-agenda.ts
- src/utils/GraphPageIterator.ts
Closes #339 
- Bugfix
The issue here was caused by couple issues:
1. The loadState method was getting called before firstUpdated. I added a flag in baseComponent to wait until firstUpdated fires before calling the method
1. The `attributeChangedCallback` was calling loadState before the setter for the property had a chance to update. I removed `attributeChangedCallback` and created setters for attributes that affect the data state. These setters now call `requestStateUpdate(true)` when changed
1. If `days` is more than few days and the calendar has more than 10 events in that timeframe, the Graph api is paged and only 10 events will be returned. Created a helper to help fetching all the events.
> Fixed mgt-agenda days not working and added support for paging

- index.html
- src/components/mgt-login/mgt-login.scss
- src/components/mgt-login/mgt-login.ts
- src/components/sub-components/mgt-flyout/mgt-flyout.ts
Closes nothing 
- Feature
I've added a `light-dismiss` property to the `mgt-flyout` subcomponent. Nobody asked for this, but I see repeated logic throughout components manually managing the visibility state of flyouts. Most of the time we simply need light dismiss logic, so pulling that functionality into `mgt-flyout` should allow us to simplify.
Assuming we all like the feature, I'll do another PR to apply it to the other components.
Inspired by the existing [`onclose` event](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onclose) used for `<dialog>` elements, `mgt-flyout` now emits an `onclose` event when the flyout is closed. This is used by calling components so they can sync their internal `isOpen` state with that of the flyout in light dismiss scenarios.
> Added light dismiss logic to mgt-flyout and implemented in mgt-login

- src/index.ts
- src/utils/TeamsHelper.ts
Closes # 
- Bugfix
I recently updated the person card to use the new TeamsHelper, but forgot to export the TeamsHelper itself. `TeamsHelper` should be exposed so that developers can set the `microsoftTeamsLib` when running in Teams. This used to be accomplished through TeamsProvider, but we split it into a helper to support our ability to separate components from providers later on.
> Exporting TeamsHelper

- src/components/mgt-person-card/mgt-person-card.ts
This PR fixes an issue where `inherit-details` on person-card do not work unless there is a signed in provider. Some develoepers depend on `inherit-details` and do not use providers which causes a breaking issue.
> Fixes inherit-details not working unless there is a signed in provider

- src/components/mgt-login/mgt-login.ts
- src/components/mgt-people-picker/mgt-people-picker.ts
- src/components/mgt-person/mgt-person.ts
- src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
- src/components/sub-components/mgt-flyout/mgt-flyout.ts
- src/graph/graph.user.ts
Closes #376 
- Bugfix
This PR fixes several issues with the bundle in IE and Edge Classic:
1. The `@query` decorator is not working in IE. Replaced everywhere with a simple getter.
2. Edge does not like catch clauses without statements, Added dummy statement everywhere
3. `getBoundRect` on IE and Edge does not contain `x` and `y` values. Switched to using `top` and `left`
> Fixes bundle issues for Edge Classic and IE

- src/components/mgt-person/mgt-person.ts
Closes #406  
- Bugfix
Firefox and some other browsers do not implement 'u' for uncicode regex. The fix adds a fallback in those browsers.
Tested in Edge, Chrome, Firefox and IE11
> Fix for unicode regex in IE/firefox

- src/components/templateHelper.ts
Closes #407  
- Bugfix
The issue was caused by the `cloneNode` function only when running in Edge in a React app. After investigation, I discovered the native `cloneNode` method was not cloning nested `<teamplate>` elements and was causing the issue in #407. This PR adds a simple cloneNode implementation that works with any element. 
Tested in Chrome, Edge, Edge Classic, Firefox, IE
> Fix for nested templates in Edge Classic

- src/components/mgt-login/mgt-login.ts
- src/graph/graph.people.ts
- src/graph/types.ts
Bugfix 
Feature
1. email Prop to IDynamicPerson
The ability to set `userDetails` on the `mgt-login` component is as follows in documentation: 
```
let loginControl = document.getElementById('myLoginControl');
loginControl.userDetails = {
displayName: 'Nikola Metulev',
email: 'nikola@contoso.com',
personImage: 'url'
}
```
However, the `mgt-person` component (leveraged in the mgt-login for render) uses the function `getEmailFromGraphEntity()` to determine which type of user object for its respective properties. User (using `mail`), Person (using `scoredEmailAddresses`), and contact (`emailAddresses`) seems to not satisfy our case for user set email. I propose we use the new `email` prop on our dynamic person, otherwise the `mail` prop on User. 
2. userDetails in loadState()
userDetails is …
> email prop added to dynamicPerson, userDetails setting issue

- src/components/mgt-login/mgt-login.ts
- Bugfix 
Presence PR introduced a new attribute avatarSize which will apply css accordingly to mgt-person and mgt-person-card. This broke login component because the attribute is not set correctly.
> Login person card css fix

- src/components/mgt-people-picker/mgt-people-picker.ts
- src/components/mgt-people/mgt-people.ts
- src/components/mgt-person-card/mgt-person-card.ts
- src/components/mgt-person/mgt-person.ts
- src/graph/graph.photos.ts
- Bugfix 
- Feature 
This PR:
1. Adds a new property/attribute to `mgt-person`
| Attribute     | Property     | Description                                                   |
| -----------   | ----------   | ------------------------------------------------------------- |
|  fetch-image  | fetchImage | Sets whether the person image should be fetched from the Microsoft Graph based on the `personDetails` provided by the user |
This was previously possible by setting `personImage='@'` which is not discoverable or good practice. This is still possible for compatibility purposes, but not documented. 
2. Fixes an issue where the person card would not be able to find an image from the graph, even if the id is available in the person details.
> Added fetchImage and fixed image fetching in mgt-person

- src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
Bugfix 
changes css variable `--input-background-color` 
**default value** from `transparent` to `white`
1. consistency with `mgt-people-picker`
2. ensures text visibility regardless of background by default
> teams-channel-picker default input background color

- src/components/mgt-person-card/mgt-person-card.ts
- src/components/mgt-person/mgt-person.ts
Closes # 
- Bugfix
This PR fixes an issue in situations where the personDetails are set by the developer and the presence is fetched based on the personDetails. However if the personDetails was set before, the old presence never gets cleared and it never gets updated. 
This issue repros in frameworks such as React where the framework changes the property of a component when properties change, but they do not rerender the component.
The fix is to clear the presence information when the personDetails are set.
> Fixed issue where presence was not getting cleared

- src/components/mgt-login/mgt-login.ts
- stories/components/login.stories.js
- Feature
This PR adds template support to mgt login, adding the following templates:
* signed-in-button-content (dataContext: {personDetails, personImage})
* signed-out-button-content (dataContext: null)
* flyout-commands (dataContext: {handleSignOut})
* flyout-person-details (dataContext: {personDetails, personImage})
> Added template support to Login Component

- src/components/mgt-person/mgt-person.ts
- src/graph/types.ts
Closes #452
Closes #445 
- Bugfix
When specifying the personDetails object manually, MgtPerson no longer throws an error when the displayName is omitted. 
In addition, the title and aria-label attributes now show the mail value (or nothing), if the displayName value is omitted. 
The component will now gracefully handle the precense/omission of displayName/mail values gracefully in all cases.
Note, this does not include the bug for providing an invalid url (#451). That will come in a follow up PR.
> Fixed error handling when setting personDetails on MgtPersonCard

- src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
Closes #443 
- Bugfix
Updated scope to get channels based on [documentation](https://docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&tabs=http)
> Update scope to get channels

- src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
Closes #441 
- Bugfix 
Center the close button
Safari:
Chrome:
> Close icon center in safari

- src/components/mgt-person-card/mgt-person-card.scss
Closes #433 
- Bugfix
Update linear gradient in css to fix safari madness...
Tested in Safari/Chrome/Edge Chromium
safari after update:
> Fix linear gradient in safari

- src/components/mgt-login/mgt-login.ts
- src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.graph.ts
- src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
- src/graph/graph.presence.ts
- src/graph/graph.user.ts
- src/utils/Batch.ts
Closes #448 
Closes #435 
- Bugfix
This PR fixes two issues with batch requests
1. Batch requests with more than 20 requests - Batch requests are limited to 20 requests at a time. The new batch helper class now splits up the requests in buckets of up to 20 requests and executes buckets in serial
2. Individual requests can be throttled in batch requests - The batch helper class now checks individual requests for throttling and adds them back to the request queue if they were throttled.
files (`npm run setLicense`)
The signature of the helper class was changed and it was updated everywhere it was used.
This PR also adds a minor fix for teams-channel-picker where archived teams were also rendered. The batch request bug was discovered thanks to this bug however, since my tenant had a ton of …
> Fixed batch calls with more than 20 requests, added retry logic

- src/components/mgt-people-picker/mgt-people-picker.scss
Closes #471 
- Bugfix
Removed an unnecessary margin value from mgt-people-picker. The bug is clearly visible in #471. Follow the steps there to see the fix.
> Removed unnecessary margin from people-picker

- src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
- src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
Closes #467 
- Bugfix 
Renders close button as the last child of the group.
Add no wrap for container
Change input background for overflow
Tested in Safari/Chrome/Edge Chromium
> Channel picker wrap && close button re-arrange

- src/components/mgt-agenda/mgt-agenda.ts
Closes #453 
- Bugfix
The issue was caused because the overwritten `requestStateUpdate` was not getting called in Edge - possibly because of an Edge bug. The fix was to not overwrite `requestStateUpdate`.
> Fixed Agenda not loading on Edge classic

- src/components/mgt-people-picker/mgt-people-picker.ts
- src/graph/graph.groups.ts
- src/graph/graph.people.ts
- stories/components/login.stories.js
- stories/components/peoplePicker.stories.js
Closes #470 
Bugfix 
Updates the people picker default search states so that if attribute `Type="Group"` will force no input to search the general graph endpoint `/groups`.
groupId attribute also has updated search state for no input.
> People picker default search state for Groups and groupId

- src/components/mgt-people-picker/mgt-people-picker.ts
Closes #436 
Bugfix 
Checks for input value so backspace isn't registered as a potential search, if there is no value. This fixes the issue with infinite loading. 
`loadstate` called upon deletion so that people list is refreshed with the available people.
> fix for backspace infinite loading, and refresh people-list upon deletion

- src/components/mgt-people-picker/mgt-people-picker.scss
- src/components/mgt-people-picker/mgt-people-picker.ts
Closes #456 
Bugfix 
Upon selection of people in the `mgt-people-picker` the people flyout will now not show unless the user refocuses in the input area. 
deletion of a selection behaves similarity now too.
> people-picker behavior on focus and selection

- src/components/mgt-people-picker/mgt-people-picker.scss
- src/components/mgt-people-picker/mgt-people-picker.ts
- src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
Closes #440 
Closes #439 
Bugfix 
7bc4f8f - Addresses key controls issue in ie11. Eight digit hex isnt supported in ie [link](https://caniuse.com/#feat=css-rrggbbaa), so fall back to rgba. `event.code` is changed to `event.keyCode` to address a similar issue of support.  
67ebbe0 - ie11 close person icon in the `mgt-people-picker` is uncentered:
fd3d13f - ie11 `teams-channel-picker` text box appears to be squished and centered towards top. (see previous picture). fix is removing `min-height` since it appears to be unsupported. 
dc96e27 - ie11 `people-picker` appears to have a permanent focus state. `requestUpdate()` added to refresh state.
> people-picker teams-channel-picker ie11 

- src/providers/TeamsProvider.ts
- Bugfix
The msal options passed to the TeamsProvider are not used when authenticating in the popup. This PR updates the TeamsProvider to pass the msal options.
> Fixed bug where msal options are not passed to msal in the TeamsProvider

- src/components/mgt-people-picker/mgt-people-picker.scss
Closes #437 
Bugfix 
- fixes overflow issue in ie11 with `overflow: hidden` 
-  **height: 100%** prevents overflow with teams channel picker overflow.
> handling picker y-overflow in ie11

- src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
- src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
Closes #473 
Bugfix 
Updates the `teams-channel-picker` to use a fluent guideline standard for flyout height of 360px. (Total for flyout, adjusted in real `px` for margin) 
Overflow is now shown by a scroll bar, which is controlled by mouse or key user interaction.
> teams-channel-picker dropdown scrolling

- samples/sp-webpart/gulpfile.js
- samples/sp-webpart/package.json
- samples/sp-webpart/src/webparts/mgtDemo/MgtDemoWebPart.ts
Closes #276 
Bugfix 
Updates our SPFx sample to support use of ie11. Uses a new `gulpfile.ts` config and additional polyfills.
> polyfills and config necessary for SPFx ie11 support

- src/components/mgt-person-card/mgt-person-card.scss
- src/components/mgt-person/mgt-person.scss
- src/components/mgt-person/mgt-person.ts
Closes #429 
- Bugfix
Added a css custom property to mgt-person. By changing this property, the background color will be set as well as the background color, border color, and icon color of presence badge. Example as below:
_**Will add PR to docs once review on the naming and approach is approved._
> Add css custom property to change mgt person background color

- .storybook/addons/codeEditorAddon/editor.js
Closes #307 
- Bugfix 
Storybook code editor settings add auto indentation.
** Please note the only meaningful change is line 183. Some auto format from linter.
> storybook code editor auto indent

- src/components/mgt-person-card/mgt-person-card.scss
Closes #518 
Bugfix
The linear gradient of the overflow for `display-name` and `job-title` properties with the `::after` selector caused the space it inherits to overflow into the entire `class=details` area. This renders the buttons, chatUser, callUser, and emailUser unusable. 
This fix will return the area back to its intended space and allow the buttons to be usable. '
**Sidenote:** I experimented with adding a story to test this, but the person-card looks to render differently in the context of a storybook window and I cannot emulate this. Open to any ideas.
> mgt-person-card callUser, emailUser, chatUser button fix

- src/components/mgt-people-picker/mgt-people-picker.scss
- src/components/mgt-person-card/mgt-person-card.scss
- src/components/mgt-person/mgt-person.scss
- src/components/mgt-person/mgt-person.ts
- Bugfix 
Updated css custom property that originally changes background color of mgt-person to only change the background/icon fill color of the presence badge. Developers will have the flexibility of changing it based on what the background-color they set up in their app.
> Update mgt-person background color css custom property

- packages/mgt/src/components/mgt-people-picker/mgt-people-picker.scss
- packages/mgt/src/components/mgt-people-picker/mgt-people-picker.ts
- stories/components/peoplePicker.stories.js
Closes #504 
Bugfix
Main purpose is to allow the close button on selected people to always be accessible, regardless of input size. This is achievable with a `position: absolute` however, ie11 has issues with combinations of `align-items` and mentioned fix positioning. The close-button and overflow are now wrapped to position along with the x for compatibility. 
Additionally I was running into the following issue, in which text would still be visible behind the close button and overflow.  :
this made the following code necessary:
```css
.selected-person {
overflow: hidden;
min-width: 100%;
}
```
Which gives it a buffer before the x button overflows, essentially making it invisible.
> people-picker overflow close-icon

- .vscode/settings.json
- packages/mgt/src/components/mgt-login/mgt-login.ts
- samples/examples/login-popup.html
- samples/examples/login-redirect-nopopup.html
Closes #609 
- Bugfix
Added another instance of `this.fireCustomEvent('loginCompleted');` to be fired on successful login completed, and added to "Sample" pages to show this working, one for popup and one for redirect
- [ x] Project builds (`yarn build`) and changes have been tested in supported browsers
- [ x] All public classes and methods have been documented
- [ x] Added appropriate [documentation](https://github.com/microsoftgraph/microsoft-graph-docs/tree/master/concepts/toolkit) [target branch `mgt/next` for new features]. Docs PR: 
- [ x] License header has been added to all new source files (`yarn setLicense`)
- [ x] Contains **NO** breaking changes
**(not sure how to test this fully, but tested both login types)**
> Fix for issue #609

- packages/mgt/src/components/mgt-people-picker/mgt-people-picker.scss
- packages/mgt/src/components/mgt-people-picker/mgt-people-picker.ts
- packages/mgt/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
- packages/mgt/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
- packages/mgt/src/components/sub-components/mgt-spinner/mgt-spinner.scss
- packages/mgt/src/components/sub-components/mgt-spinner/mgt-spinner.ts
Closes #611 
- Refactoring (no functional changes, no api changes) 
We use loading spinners in a few components, and it is needed again in the person card update. Instead of copy/pasting the spinner in, I thought it would make more sense to extract it into it's own sub-component, and then consume it that way.
This PR covers the extraction of the spinner code into it's own *mgt-spinner* sub-component. I've also updated the other components to use the new mgt-spinner instead.
> Added mgt-spinner sub-component

- packages/mgt/src/components/mgt-tasks-base/mgt-tasks-base.scss
Closes # 
- Bugfix
Somewhere in the creation of mgt-todo, I deviated from the styles in the original mgt-tasks. The effect is that task metadata aligns in odd ways in tablet and mobile view.
To fix it I just copied the good styles from mgt-tasks over into mgt-todo. Tadaa! They should act the same now 👍
mgt-tasks
mgt-todo (old)
mgt-todo (new)
> Fixed metadata alignment in mgt-todo

- packages/mgt/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #614 
Bugfix 
This fix ensures that the people picker search only searches within members of the group even when there is an input search query in the text box. I have also modified the renderHighlightText() function to display the name in the case where the search query is not present in the name (It could be in the email ID).
> Fixed people picker search

- packages/mgt/src/components/mgt-person-card/mgt-person-card.scss
Closes #641 
- Bugfix
I fixed the card alignment as described in the issue by defining `grid-template-areas`.
> Fixed alignment in person card

- packages/mgt/src/index.ts
Closes #651 
- Bugfix
The mgt packages should re-export the factored out packages to ensure the bundle remains compatible with 1.x and work the same way. This PR exports `@microsoft/mgt-element` from `@microsoft/mgt` so the Providers namespace is still available.
> exporting mgt-element from mgt

- packages/mgt/src/components/mgt-person-card/sections/mgt-person-card-organization/mgt-person-card-organization.ts
- packages/mgt/src/components/mgt-person/mgt-person.scss
Closes #632 
- Bugfix
The user-avatar icon was previously rendering to fill the available space, and it looked odd (pics in issue #632). To make it look a bit better, I shrunk the font-size of the person icon to be 50% of whatever the avatar-size is.
I also updated the person-card organization section to pass the proper data to mgt-person. This fixes the bug where the avatar -icon was showing up even when initials should have worked. 
A great way to test this is to check out the sample page for person card: 
`http://localhost:3000/samples/examples/person-card.html`
> Fixed rendering of user-avatar and initials in person/person-card

- packages/mgt/src/components/mgt-agenda/mgt-agenda.ts
- Bugfix
Added the `type` attribute to the `events` property on Agenda. Without this attribute, you cannot set the `events` attribute in HTML and have it map correctly to the `events` property.
In other words, doing something like this:
```
<mgt-agenda events="<JSON array of events>"></mgt-agenda>
```
Would not work, the component would render nothing.
See "Convert from attribute to property" at https://lit-element.polymer-project.org/guide/properties
> Added type attribute to events property on agenda component

- packages/mgt/src/providers/ProxyProvider.ts
- Bugfix
Proxy provider makes a call to `me` to check whether the service is signed in or not. However, because it was using the `getMe` method, the call was being cached. This PR makes sure the call does not get cached and is always made.
> Fixed issue where me call was cached in Proxy Graph

- packages/mgt/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #677 
Bugfix
adds `this.fireCustomEvent('blur')` to mgt-people-picker, person selection functionality so that either selection method (key or mouse) fires blur event. This event was previously escaped by preventDefault() to cancel tab navigation.
> [people-picker][bug] fires blur event on selection of person

- .storybook/manager-head.html
Closes #692 
- Bugfix 
This is after the re-scan and new rules around EU cookies and banners MSFT has implemented. I had consulted with the team that handles Cookie categorization on WCP. Now that the analytics cookie is deemed 'essential'. EU cookie banner can be removed. No consent needed.
> Remove EU cookie banner

- packages/mgt/src/components/sub-components/mgt-arrow-options/mgt-arrow-options.scss
Closes #620 
- Bugfix
This will fix the font in mgt-tasks and mgt-todo header
> Update to use default font family in mgt-arrow-option to fix mgt-tasks font

- packages/mgt/src/components/mgt-person/mgt-person.ts
Closes #690 
- Bugfix
This PR fixes an issue where the component would not update it's data if the `personQuery` or `userId` properties changed. However, it would work if the attributes were changed. The issue was fixed by moving the state update request to the properties setters instead
> Fixed issue where person would not update when personQuery and userId properties change

- packages/mgt/src/components/mgt-person/mgt-person.ts
- packages/mgt/src/graph/graph.presence.ts
Closes #695 
Bugfix
Updated `getUserPresence` to call the `/me/presence` endpoint and use only the `Presence.Read` permission for current signed in user.
Also deleted the `getMyPresence` function since it was never used
> Fixed mgt-person to only require 'Presence.Read' for current signed in user 

- packages/mgt/src/components/mgt-agenda/mgt-agenda.graph.ts
- packages/mgt/src/components/mgt-agenda/mgt-agenda.ts
Closes #681
- Feature
Extends mgt-agenda with a new property named `preferred-timezone` which allows developers to specify the preferred timezone to be used when retrieving events from Graph.
n/a
> Adds support for preferred timezone in mgt-agenda.

- packages/mgt-react/src/Mgt.ts
- packages/mgt-react/src/MgtTemplateProps.ts
- samples/react-app/src/index.js
Closes #713 
Feature
Updated `mgt-react` to assume the template value is `default` if no template value is provided
> Assume default template for mgt-react

- packages/mgt-components/src/components/mgt-tasks-base/mgt-tasks-base.scss
- packages/mgt-components/src/components/mgt-tasks-base/mgt-tasks-base.theme.scss
Closes #828 
- Bugfix 
--task-border did not exist before 🤷🏻‍♀️
> Add --task-border property

- packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
- samples/examples/simple-provider.html
Closes #816
Bugfix 
Updates the display property to flex, for the selector:
```
.team-chosen-input[contenteditable]:empty::after
```
Browsers (such as firefox) seemed to be handling the input line height differently. So if a user selects a team, and then wishes to change the selection, the cursor will still appear to be on same baseline. 
Testing this seems to be mostly reproducible in storybook.
> teams-channel-picker display property for firefox bug

- packages/mgt-components/package.json
- packages/mgt-element/package.json
- packages/providers/mgt-msal-provider/package.json
- packages/providers/mgt-proxy-provider/package.json
- packages/providers/mgt-teams-provider/package.json
Closes #847  
- Bugfix
This PR adds the missing dependency to the Microsoft Graph Client to all packages
> Added graph client dependency to packages that use it

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.scss
- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
- packages/mgt-components/src/components/sub-components/mgt-flyout/mgt-flyout.ts
Closes #792  
- Bugfix
This PR fixes the people picker flyout rendering on top of the people picker by:
1. Updating the flyout layout logic to avoid hiding the anchor when open
2. Adding an internal css property for setting the max-height of the flyout contents when needed
2. Updating the people picker component to leverage the max-height css property
3. Updating the logic of the people picker dropdown to scroll and bring items to view when focused
> Fixed people picker flyout layout

- packages/mgt-react/scripts/generate.js
- packages/mgt-react/src/generated/react.ts
Closes #760 
Bugfix
Adds the className and id property to the mgt-react package allowing typescript users of the package to use the property
> Add className and id property to typescript react props

- packages/mgt-components/src/components/mgt-person/mgt-person.ts
Closes #755 
Feature
Added the fallback method `findUsers` in `mgt-person` component to search _/users_ endpoint when the requested person is not returned using the _/people_ endpoint
> Mgt-Person: Added fallback method to search /users endpoint

- packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
- packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
Closes #835 #840 
Bugfix
Separates the "selected" state search icon and "not-selected{" state search icon, to handle different overflow issues. 
Important to test in all supported browsers.
> [bug] [mgt-teams-channel-picker] overflow fix

- packages/mgt-components/src/components/mgt-person/mgt-person.ts
- packages/mgt-components/src/graph/graph.user.ts
Closes #755 
Feature
Updated the `mgt-person` component to use the fallback method `findUsers` to search `/users` endpoint when the requested person is not returned using the `/people` endpoint. Also updated the `findUsers` method to search users by `displayName` and `email` (Ref https://github.com/microsoftgraph/microsoft-graph-toolkit/pull/860#issuecomment-754886369).
> Mgt-Person: Added fallback method to search /users endpoint and updated findUsers method

- packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts
Closes #865 
Bugfix
Sets person-card state to null for user-id changes so that `loadState()` is called and the card is refreshed with the new user.
> [bug] [mgt-person-card] userid property fix

- packages/mgt-react/src/Mgt.ts
Closes #760 (this is an optional PR to the closed issue, but this PR includes all missing html attributes, not just few of them)
Bugfix
Refactoring (no functional changes, no api changes) 
build the packages to test 
This screenshot shows intelligence without the properties
This screenshot show intelligence with the properties after this PR
> add react html attributes to the component properties

- packages/mgt-components/src/components/mgt-person/mgt-person.ts
- packages/mgt-react/src/generated/react.ts
- stories/components/person.stories.js
Closes #790 
- Feature
I've added the ability to provide templates to override the lines 1/2/3 portions of the component. Click events should continue to work, even with templates. Also, all templates have the `{{person}}` object available.
With/without templates:
Implement like so:
```
<mgt-person person-query="me" view="threeLines" person-card="hover" show-presence>
<template data-type="line1">
<div>
Hello, my name is: {{person.displayName}}
</div>
</template>
<template data-type="line2">
<div>
Super cool
</div>
</template>
<template data-type="line3">
<div>
Loves MGT
</div>
</template>
</mgt-person>
```
I didn't explicitly add the `avatarType` to the react package, but it got generated during build. It should probably be committed.
> Added templates for metadata lines in person

- packages/mgt-components/src/components/mgt-todo/mgt-todo.ts
Closes #879  
- Bugfix
We used the wrong string format when saving new tasks with due dates. I've fixed todo to use `getLocaleDateString` instead of `getISOString`.
> Fixed bug in saving new todo task datetime

- packages/mgt-components/src/components/mgt-person/mgt-person.ts
- packages/mgt-components/src/components/sub-components/mgt-flyout/mgt-flyout.scss
- packages/mgt-components/src/components/sub-components/mgt-flyout/mgt-flyout.ts
Closes #877  
- Bugfix
This PR adds a workaround by using two `scout` divs to detect when the flyout will not be positioned correctly before it is positioned, and uses the offset of those `scouts` to account for the new stacking context and apply the right position coordinates.
> Fixed flyout position when used in a parent with css transform

- packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
- packages/mgt-element/src/Graph.ts
- packages/mgt-element/src/mock/MockProvider.ts
- packages/mgt-element/src/providers/IProvider.ts
- packages/mgt-element/src/providers/SimpleProvider.ts
- packages/mgt-element/src/utils/SdkVersionMiddleware.ts
- packages/providers/mgt-electron-provider/src/Provider/ElectronProvider.ts
- packages/providers/mgt-msal-provider/src/MsalProvider.ts
- packages/providers/mgt-proxy-provider/src/ProxyProvider.ts
- packages/providers/mgt-sharepoint-provider/src/SharePointProvider.ts
- packages/providers/mgt-teams-provider/src/TeamsProvider.ts
Closes #728 
- Other... 
This PR adds the provider name to the SdkVersion header for analytics
Example request:
```
SdkVersion: MGT-TEAMS-CHANNEL-PICKER/2.2.0, MgtMsalProvider/2.2.0, mgt/2.2.0, graph-js/2.2.1 (featureUsage=6)
```
> Added provider name to SdkVersion header

- packages/mgt-components/src/components/mgt-file-list/mgt-file-list.ts
- packages/mgt-components/src/components/mgt-file/mgt-file.scss
- packages/mgt-components/src/components/mgt-file/mgt-file.ts
Closes #984 #983
Feature 
Adds rtl for the two components:
`mgt-file-list`
`mgt-file` 
There wasn't much to add due to @beth-panx 's excellent css, just a fix for the number labels "01." 
I tested scenarios in the stories and some templating.
> rtl for mgt-file-list and mgt-file

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #1001
Bugfix
Fixes a few issues surrounding accessible tab traversal for a `mgt-people-picker` component. 
1) When user taps "tab" 2x (twice) inside the input-box, the flyout will properly hide, and be unfocused. Previously, the flyout would appear and display error message. 
2) "shift + tab" to back out of the input-box to access elements above or below
3) loads people when tabbed (related to #1001) 
This should help alleviate some of the accessible traversal until we redesign or add visible targets. example:
```html
<h2 tabindex="0">test</h2>
<mgt-people-picker></mgt-people-picker>
<h2 tabindex="0">test</h2>
```
Should be easily traversable with tab, or shift+tab
> [mgt-people-picker] tab control 

- packages/mgt-components/src/components/mgt-file-list/mgt-file-list.ts
- packages/mgt-components/src/components/mgt-file/mgt-file.ts
Closes #1015 
- Feature 
Related to #720
> [mgt-file] [mgt-file-list] Add required scopes static getter

- packages/mgt-components/src/components/mgt-file-list/mgt-file-list.ts
Closes #1027 
- Bugfix
This fix allow to refresh FileList control when property PageSize is changed by code described in #1027.
> [Mgt-File-List] refresh property PageSize when changed by code.

- packages/mgt-components/src/components/mgt-file/mgt-file.ts
Closes #1026 
- Bugfix
Added additional condition to validate if file is "driveItem.package.type === 'oneNote'".
If yes then return associate docicon 'onetoc' else returns 'Folder'
> [mgt-file] Include OneNote Icon when driveItem.package is type 'oneNote'

- packages/mgt-components/src/graph/graph.userWithPhoto.ts
This is a follow up form #1051 
- Bugfix
I noticed that if a photo is already cached, but a user is not, the call to get the user from the graph is malformed. This PR fixes that issue.
> Fixed getUserWithPhoto when photo is already cached

- .github/workflows/push-release.yml
- .github/workflows/push.yml
- .github/workflows/storybook.yml
- package.json
This PR adds two new workflows 
1. storybook.yml - whenever changes are pushed to the `main` branch, a new version of mgt.dev will be automatically published to mgt.dev/next for testing and demo purposes. 
2. push-release - whenever changes are pushed to the `release/latest` branch, this workflow will 
- auto publish mgt.dev
- publish a new release to npm if the version of package.json is different to what is already published - before publishing, an administrator will have to approve the workflow from running (this is currently commented out until we can test it out during next release)
> Added two new workflows to automate storybook and npm publishing

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
- packages/mgt-components/src/graph/cacheStores.ts
- packages/mgt-components/src/graph/graph.groups.ts
- packages/mgt-element/src/utils/Cache.ts
- packages/mgt-react/src/generated/react.ts
- stories/components/peoplePicker.stories.js
Closes #1065
Feature
The newly added `default-selected-group-ids` complements the already existing `default-selected-user-ids`. It allows initializing the People Picker component with pre-selected groups. A use case for this would be an edit page that loads user IDs and group IDs from a database for the end-user to edit the selection of users and groups.
> Add default-selected-group-ids attribute for People-Picker component

- packages/mgt-components/src/graph/graph.files.ts
Closes #1130 
- Bugfix
A regex expression in file graph.file breaks build for Safari
> Fix regex for safari

- packages/mgt-components/src/components/mgt-get/mgt-get.ts
- packages/mgt-components/src/graph/graph.files.ts
Closes #1218
- Feature
Adds support for loading document thumbnails with mgt-get
~~While the project builds and the changes seem to be okay, I couldn't fully test them. The storybook proxy doesn't seem to return document thumbnails and there are no instructions how to test the bundle locally. Is there a way for us to see it in action before merging @nmetulev?~~
I found the build:bundle script in the mgt package and was able to test the bundle locally. All seems to be working as intended.
> Adds support for loading document thumbnails with mgt-get. Closes #1218

- packages/mgt-components/src/components/mgt-get/mgt-get.ts
- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
- stories/components/get.stories.js
Closes #1183
Bugfix
Adds a new private variable `refreshType` to change whether the loading template is displayed during a `refresh()`
Loading templates still display if uninitialized or set to `refresh(true)` 
Example:
```html
<mgt-get cache-enabled="true" resource="/me/presence" version="beta" scopes="Presence.Read">
<template data-type="default"> {{availability}} </template>
<template data-type="loading">
<h2>Loading...?!?!</h2>
</template>
</mgt-get>
```
```js
//console
let get = document.querySelector('mgt-get')
get.refresh(false)
///will not display loading template
get.refresh(true)
//displays loading template
```
> [mgt-get] variable "presentational" loading template with refresh 

- packages/mgt-element/src/components/templatedComponent.ts
- packages/mgt-element/src/utils/TemplateHelper.ts
Closes #1226  
- Bugfix
The `templateContext` was not getting passed to the `templateRendered` event, and it was not exposed in the React templates. This PR fixes the issue by always passing the `templateContext` along side the data context.
Even though the `renderTemplate` method from TemplateHelper is public, it is meant to only be used internally and is not a documented method that we support - changing this method should not be considered a breaking change.
> Fixed templateContext not getting passed to templateRendered event

- packages/mgt-components/src/components/mgt-tasks-base/mgt-tasks-base.scss
Changed the css to address the TaskTitle overflow when the text is long.
Closes  #1274 
Bugfix 
Changed the White-Space css property  on the TaskDetailsContainer class from nowrap to normal
> Fixed issue with overflow text on task title

- packages/mgt-components/src/styles/shared-sass-variables.scss
- stories/components/peoplePicker/peoplePicker.style.js
Closes #1113 
- Bugfix
Fixed `--input-border-`* custom properties for people picker and teams channel picker.
Fixed by creating a dependency to the `--input-border` property to all `--input-border-*` properties and only using `border-*` properties in our css. For example, here is how the border properties are now set for the people picker:
```css
border-left: var(--input-border-left, var(--input-border, "default value")) 
border-right: var(--input-border-right, var(--input-border, "default value")) 
border-top: var(--input-border-top, var(--input-border, "default value")) 
border-bottom: var(--input-border-bottom, var(--input-border, "default value")) 
``` 
Notice we are no longer setting a `border` property since the other border properties will cover it.
> Fixed --input-border-* custom properties

- packages/mgt-element/src/components/templatedComponent.ts
Closes #1263 
- Bugfix
Fixed issue where templates would not re-render when the template context is changed by making sure the data context equality check also includes the template context
> Fixed templateContext changes not re-rendering templates

- packages/mgt-components/src/components/mgt-agenda/mgt-agenda.ts
Closes #1289  
- Bugfix 
Fixed the agenda header dates for All day events.  Event times are adjusted for the user's timezone except for All day events.  The fix passes the ISO string with the appropriate time for the user's timezone to the getDateHeaderFromDateTimeString function which subtracts the timezone offset.
- [ x ] Project builds (`yarn build`) and changes have been tested in at least two supported browsers (Edge + non-Chromium based browser)
- [ x ] Contains **NO** breaking changes
> fixed agenda header dates for all day events

- packages/mgt-components/src/components/mgt-file-list/mgt-file-upload/mgt-file-upload.scss
- packages/mgt-components/src/components/mgt-file-list/mgt-file-upload/mgt-file-upload.theme.scss
- packages/mgt-components/src/components/mgt-file-list/mgt-file-upload/mgt-file-upload.ts
Closes #1308 
Closes #1306
Closes #1304 
- Bugfix 
Bug Fix #1308 -  Safari doesn't support JavaScript properties style changes ".style.display", was updated to use .classList like other components.
Bug Fix #1306 - include method clearFilesCache() when file is uploaded with success. V2 of component should analyze cache entries and update/add if entry doesn't exist.
Bug Fix #1304 - Styles (clickable ) where included only on successfully uploaded files.
**Bug Fix #1305** - Require feedback from @beth-panx, base on our design when user upload files then gets a visual report. When user uploads new files, info of upload files are overwritten. The main idea was to don't let the upload report grow in to the moon. Base on moderators feedback a new commit could be needed from my side.
> Fixes #1308 #1306 #1304

- packages/mgt-components/src/components/mgt-person/mgt-person.ts
Closes #1328
Bugfix 
Renames the `personProperties` value previously passed to the line1 templates, to `person` to match the documentation for features and our previous.
> [mgt-person][bugfix] Return lineprop context name to person

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #1398  
- Bugfix 
When the `selection-mode="single"` the `clearInput()` function was setting the input value to an empty string. This caused a `TypeError` because the input was a `null` value. This fix ensures that the input value is only reset in multiple selection mode only.
> Set the input text to empty only on multiple mode

- packages/mgt-components/src/components/mgt-person/mgt-person.ts
- packages/mgt-components/src/graph/graph.user.ts
Closes #1396 
Bugfix
1. fixes issue with the people-picker retrieving a "me" value from getUsersFromUserIds. Previously it would only find data for the user from the cache in login. 
2. "me" wasn't producing personType results, so updating the clause for team photo vs person photo
> [people-picker] user-ids fix for 'me' request 

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.scss
- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #1117  
- Bugfix
Added support for the names of the selected people to be narrated by the screen reader.
Use the steps in the video of #1117 to test.
> Add ac11y support for the people-picker to narrate selected people

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #1117
Bugfix 
Test by implementing a `mgt-people-picker` control.  
selecting person, use the tab index to traverse.
> [people-picker] fix for selected people focusable area, removing from normal mgt-person

- .storybook/manager-head.html
- stories/feedback.stories.mdx
- stories/overview.stories.mdx
Closes #1525
- Bugfix
Fixing the fact we had multiple H1 on the same page since we released the Overview + Feedback.
> Fixing h1 and alt on images

- packages/mgt-element/src/utils/TemplateHelper.ts
Closes #1588
- Bugfix
Change the regex to use a non-greedy quantifier. This should prevent matching of white spaces from taking a long time in some _long_ strings. Should also quell the security alert https://github.com/microsoftgraph/microsoft-graph-toolkit/security/code-scanning/30
> Fix regex to avoid Polynomial time and fix security alert

- packages/mgt-components/src/graph/graph.groups.ts
Closes #1634  
- Bugfix
The URL for requesting the groups was being formed incorrectly because the `filterQuery` value was being duplicated. In scenarios that it is empty, the URL will have unnecessary ` and ` values that break the request URL. This fix ensures that the additional parameters are correctly set when creating the request URL.
> [people-picker] Fix setting the filterQuery value for complete request URL paths.

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
- packages/mgt-components/src/graph/graph.user.ts
Closes #1662  
- Bugfix
Searching in the `people-picker` with `user-ids` set gave results that are not part of the `user-ids` listed. This fix ensures that the displayed users and the search results are from the `user-ids` only.
> [people-picker] Search users only set in the user-ids when user-ids are set

- .storybook/manager-head.html
Closes # 
- Bugfix
Loading functions for https://mgt.dev/next in `manager-head.html` file was failing because of multiple calls of `window.onload`. This was done during conflict resolution in 3f6085af64d4a6f9b3e9313eb305508b4426a8d7. Hence, `npm` and `GitHub` images were not visible and other functionality.
> Call all the methods required in window.onload once

- packages/mgt/src/bundle/mgt-loader.js
Closes #1699  
- Bugfix
By default, loading the script using the inline method makes the script loading async. Hence, setting the async attribute makes it fail for instances where the loader is not set to work async. More details [here](https://developer.mozilla.org/en-US/docs/Games/Techniques/Async_scripts#putting_async_into_action).
> Remove adding the async attribute to the mgt loader

- package.json
- packages/mgt-components/src/components/mgt-login/mgt-login.ts
- packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts
Closes #1715 , closes #1584 
- Bugfix
This allows the login component to have an encapsulating button which has an `aria-label` that is set depending on whether a user is signed in (sets the `displayName`) or signed out (sets the 'Sign In' string). The `aria-label` is maintained when you override the various templates.
> Set the aria-label text for the buttons

- packages/mgt-element/src/utils/LocalizationHelper.ts
Closes #1785 
Bugfix
If a provider is in the head using mgt-loader the synchronous loading of mgt scripts causes LocaliztionHelper to attempt to access the body DOM node of the document before the browser has parsed the entire document causing body to be null. Using optional chaining avoids trying to call a method on a null object.
> fix: prevent unsafe access to dom nodes in getDocumentDirection

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #1763
Bugfix 
Adds special handling for keyUp when pasting to resolve email addresses
> fix: email resolution on paste for people picker

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #1795
Bugfix
Reverts a, probably accidental, change in #1652 that moved a call to `getUsers`. This change led to an empty `if`-statement and the `user-ids` and `people-filters` properties not working properly.
> Revert move of getUsers, fixes #1795

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #1796
Bugfix
The `defaultPeople` property, if set, is used when rendering the flyout menu. This property is set once and never updated, even if the underlying properties that filled that list are changed. This resulted in the issue described in #1796.
This PR adds a change that clears the `defaultProperty` in the `requestStateUpdate` function, if it is called with `force=true`. The `requestStateUpdate` function is called by almost all of the properties in the people picker, when their value has changed, and therefore this PR fixes the caching issue for those properties as well.
> People picker - Remove indefinite caching of flyout menu contents

- .storybook/manager-head.html
- .storybook/preview-body.html
Closes #1813 
- Bugfix
updates custom css selectors to fix color contrast, changes in the Storybook package resulted in a regression.
A11y approval is assumed as this addresses a regression and has not wider impact.
> fix: correct css overrides for contrast issues

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #1631  
- Bugfix
Changes the child element roles to `listitem` whose parent role is `list`.
> update: Set child element roles to listitem when parent role is list

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #1632 
- Bugfix
Remove the `id` attribute on the dropdown list. It's causing an id conflict with the child elements that have the id declared as the `displayName` also.
> update: Remove unused id attribute causing id conflicts

- .storybook/manager-head.html
Closes #1535  
- Bugfix 
Allow the tab key to land only once on the heading in the storybook playground.
> update: Focus on the heading link once in the storybook playground

- packages/mgt-components/src/graph/graph.userWithPhoto.ts
Closes #1850  
Add support for error code `ImageNotFound` which MSGraph API returns when fetching photo.
> fix: include ImageNotFound error code to avoid unnecessary refetching

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
- packages/mgt-components/src/components/mgt-people-picker/strings.ts
Closes #1898 
Bugfix
Refactoring (no functional changes, no api changes)
This PR updates the People Picker selected people close button for better a11y support.
-  `role="button"` added to element
-  `removeSelectedItem: 'remove selected item'` added to `strings.ts`
-  `aria-label` updated to include `removeSelectedItem` string and `person.displayName`
> Fix for people picker selected people close button a11y

- packages/mgt-element/src/providers/IProvider.ts
- packages/providers/mgt-msal2-provider/src/Msal2Provider.ts
Closes #1930
- Bugfix 
A regression removed the functionality to correctly use an explicitly provided Msal PublicClientApplication originally delivered in #1181.
This fixes the regression, cleans up repeated code, and adds missing doc comments
> fix: restore provided msal public client behavior

- .github/workflows/next.yml
- .github/workflows/pr-clean-storybook.yml
- .github/workflows/pr-storybook.yml
- .github/workflows/pr.yml
- .github/workflows/push-release.yml
- .github/workflows/push.yml
- .github/workflows/storybook.yml
Closes #1938 
- Bugfix
- 
Updates all pipelines to use node 14.x to build articacts
Should allow open PRs to build successfully again
> chore: update build pipelines to use node v14.x

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #1934
Bugfix
Update groupIds prop of PeoplePicker component to string[] to fix error. Also moves in line with other similar fields like userIds,  defaultSelectedUserIds and defaultSelectedGroupIds. Documentation probably needs to be updated for all 4 of these fields as they ALL say to provide 'string of comma-separated...' which must be legacy as they are all now string[] rather than comma separated strings.
All 4 of these props also have what looks to be legacy converters to separate the strings by comma separator, which is probably not needed anymore but I haven't touched these... (`return value.split(',').map(v => v.trim());`)
> update groupIds prop of PeoplePicker to string array

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.scss
- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
- packages/mgt-components/src/styles/shared-sass-variables.scss
- stories/components/peoplePicker/peoplePicker.style.js
Closes #1888  
- Feature
- Added two new custom CSS properties for use in the mgt-people-picker:
- `--dropdown-item-text-color` customizes the text color of the dropdown items.
- `--dropdown-item-text-hover-color` customizes the text color of the dropdown items during hover
In windows, when you enable high contrast themes, the text colors are set to white or black by default. Hence, testing this with issue #1888 is a challenge. Therefore, I'm requesting the issue other to verify if this solution fixes their issue.
> feat: add new CSS properties for the people picker

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Adding an aria-label property that can be set on the people picker component to allow a visual label to match the label of the component
Closes #1899 
- Bugfix
Added a property called `aria-label` that can be passed in to the component which sets the aria-label on the people picker input.
> Adding an aria-label property that can be set on the people picker component to allow a visual label to match the label of the component

- packages/mgt-components/src/components/mgt-person/mgt-person.ts
Closes #1593  
- Bugfix
When you try to check for the id from `this.personDetailsInternal` only, the value will be `undefined` in the event `personDetails` were set on the component. To mitigate getting the default presence value, I update the instances that the `loadState` method updates the person's details. This ensures the final call to get the presence has either a user ID to make the call, it calls the `/me` endpoint or it falls to the default presence value.
> fix: set the person details in all blocks when loading state

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.scss
Closes #1950 
- Bugfix
This fix ensures that the color of the text on the dropdown item is set whenever you hover or focus anywhere on the dropdown item.
> fix: set the hover and focus color on the dropdown item

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #1962 
- Bugfix
Fixed rendering of aria-label in the people picker component
> fix: make people-picker aria-label work in firefox

- packages/mgt-element/src/IGraph.ts
- packages/mgt-element/src/utils/GraphHelpers.ts
- packages/mgt-element/src/utils/SdkVersionMiddleware.ts
Closes #1621  
- Bugfix
This happens during large file upload as some endpoints throw a CORS error when the SdkVersion header is attached. This change deletes the header from the request object when the request endpoint is a non-graph endpoint.
> fix: remove the SdkVersion header when redirected to a non-graph endpoint

- .github/workflows/push-release.yml
> chore: send notification to teamsfx when new version released

- stories/components/peoplePicker/peoplePicker.properties.js
Closes #2002
- Bugfix
Simple bug fix.
> fix: fix dynamic group id people picker story

- package.json
- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
- samples/react-app/src/App.tsx
- stories/components/peoplePicker/peoplePicker.properties.js
Closes #1644 
- Bugfix 
fixes state update triggers in people-picker
updating react sample app to test functionality
adds story to show async setting of defaultSelectedUserIds property
> bug: people picker state management

- packages/mgt/src/bundle/mgt-loader.js
logs a warning to the console when mgt-loader is used without semver or tag from unpkg
Closes #2031  
- Feature
> feat: mgt-loader version warning

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.scss
makes the focus indicator visible on webkit browsers when attempting to remove an item from the people picker selected list
Closes #1949  
- Bugfix
> bug: unselect person focus indicator on webkit

- .storybook/preview.js
Closes #1642
- Bugfix 
Removes a button that does nothing.
> fix: hide storybook canvas button

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #2155  
- Bugfix
Call `this.requestUpdate()` after setting `selectedPeople` to trigger displaying the set people.
> fix: request state update after setting selectedPeople

- packages/mgt-spfx-utils/package.json
Closes #2174
- Bugfix 
Add dist folder to tarball created when publishing to npm
> bug: fix mgt-spfx-utils packing

- samples/sp-webpart/package.json
Closes #2175 
- Bugfix 
Removes mgt-spfx from sp-webpart dependencies as it's not being used with disambiguation
> bug: remove mgt-spfx dependency from react webpart sample

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #2143 
- Bugfix 
options in people picker suggestions now include job title or mail in aria-label
> fix: people picker option labels

- packages/mgt-components/src/components/mgt-person/mgt-person.ts
- stories/components/person/person.properties.js
Closes #2120
- Bugfix
Conditionally removes tabindex attribute allowing voice over to see inside the html for mgt-person when nested inside an html element with the role menuitem
> fix: voice over for person in list

- packages/mgt-components/src/components/mgt-tasks/mgt-tasks.ts
- packages/mgt-components/src/components/mgt-tasks/task-sources.ts
- packages/mgt-components/src/graph/graph.user.ts
- stories/components/tasks.stories.js
Closes #2141 
- Bugfix
- Feature 
- Passed down the `group-id` vlue if it is set in `mgt-tasks`.
- Fixed storybook import bug for tasks.
- Fixed bug with returning null from `mgt-people` when there are no batch requests and the people values are fetched from the cache.
- Updated storybook for tasks with `group-id` story.
> feat: optionally pass the group-id value from tasks to people picker

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #2210 
- Bugfix
nullish coalesce to an empty string when interpolating the aria-label
> fix: prevent undefined in people-picker option labels for line two

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.scss
- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
- packages/mgt-components/tsconfig.json
Closes #2218
- Bugfix 
sets focus on the currently selected item when using keyboard to chose a person
uses focus styling
fixes an issue which would cause the page to scroll when navigating in the suggestions list
Focus behavior in Firefox:
Focus behavior in Edge
> fix: people-picker set focus on list navigation

- .github/policies/branch-protection.yml
I'm curious whether **Clean pr storybook** and **Deploy pr storybook** will optionally run? We should verify that these are skipped in a PR.
@gavinbarron can you verify that I have the correct required checks?
One thing we learned here is that we need to capture the required checks from branch protection UI before we change it here. Otherwise we need to review all of the GitHub workflows for applicability. Taking this  broadly, **before** we apply policy at the org-level for repos, we should capture the existing repo policy so that we are clear what we lose when the policy service clears the settings.
> Add branch protection policy for next/* branches

- .github/policies/branch-protection.yml
editing require status check to use full name of node 16.x build
> chore: branch policy update

- .storybook/addons/codeEditorAddon/codeAddon.js
- .storybook/preview-head.html
- stories/components/agenda/agenda.style.js
- stories/components/login/login.styles.js
- stories/components/people/people.styles.js
- stories/components/peoplePicker/peoplePicker.style.js
- stories/components/tasks/tasks.style.js
Closes #2240  
- Bugfix
Removes the theme toggle from the custom CSS properties story and templating pages. These pages are customized hence we default to a light mode in the playground.
> fix: remove theme-toggle capability from custom CSS property and templating stories

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #2320 
- Bugfix
Removes unnecessary prefix on suggested people list items
> fix: suggested people aria labels

- packages/mgt/package.json
Closes #2333 
- Bugfix 
Adds @microsoft/mgt-mock-provider as a dependency in package.json of @microsoft/mgt
> fix: include mgt-mock-provider as dependency to mgt

- packages/mgt-components/src/components/mgt-file-list/mgt-file-upload/mgt-file-upload.ts
Closes #2357
- Bugfix
Convert maxFileSize in the mgt-file-upload component when calling formatBytes() method.
None
> fix: Update mgt-file-upload.ts

- .storybook/manager-head.html
Closes #2247 #2245
- Bugfix
moves the footer into the side bar and makes links in the footer focusable
> fix: storybook footer accessibility

- packages/mgt-components/src/components/mgt-tasks/mgt-tasks.scss
- packages/mgt-components/src/components/mgt-tasks/mgt-tasks.ts
Closes #2316  
- Bugfix 
ensures fluent components are properly registered
adds styling to wrap new task inputs when needed
> fix: new task select rendering

- index.html
- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
- packages/mgt-components/src/styles/theme-manager.ts
Closes #2327 
- Bugfix
now sets design token values via functions exposed by fluent to ensure they are used inside nested cards
> fix: change override design token logic

- .storybook/addons/codeEditorAddon/editor.js
Closes #2248  
- Bugfix 
makes visual tabs in editor behave like aria tabs
> fix: editor tabs keyboard navigation

- packages/mgt-element/src/utils/version.ts
- packages/mgt-react/package.json
Closes #2392
- Bugfix 
Set semver range for React peer dependency
This is linked to #2063
The semver range of ^17.0.1 || ^18.0.0 was tested using https://semver.npmjs.com/
> fix: set react peer dependency as range

- stories/components/preview/searchBox/searchBox.a.js
Closes #2394
- Bugfix
Switching to `mgt-search-results` in the selector
> fix: using mgt-search-results instead of mgt-search-box

- scripts/setVersion.js
Fix to spfx publishing script to allow for correct publishing when version being published uses the `-rc.*`  suffix
> fix: make spfx version script work for rc version

- packages/mgt-components/src/graph/graph.files.ts
Closes #2147  
- Bugfix
Added top to the file-list caching key signature. This allows for variable and unique keys to use to cache when you vary the page-size attribute for the file-list.
Keys will look like this in indexDb: Example for getting files from my drive:
> fix: add top to the file-list cache key signature

- packages/mgt-components/src/components/mgt-login/mgt-login.scss
- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.scss
- packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
Closes #2339  
Bugfix
Fixes text spacings on login, channel-picker and teams-channel-picker when using Stylus
> fix: enable text spacings on login, channel-picker and teams-channel-picker

- index.html
- packages/mgt-components/src/components/mgt-login/mgt-login.ts
- packages/mgt-components/src/components/sub-components/mgt-flyout/mgt-flyout.ts
- stories/components/login/login.stories.js
Closes #2269 
Closes #2354 
- Bugfix
Sets the aria-expanded attribute of the button rendered when a user is signed in
Fixes the positioning of the pop-up when the button is on the right of the screen and is narrower than the pop-up
> fix(a11y): set aria-expanded for mgt-login when open/closed

- packages/mgt-chat/src/index.ts
- packages/mgt-chat/src/statefulClient/GraphNotificationClient.ts
- samples/react-chat/src/index.tsx
- yarn.lock
Closes #2365  
- Bugfix
exports config object for graph notifications to allow for applications to supply their own GNB url and appId
> fix: export notification broker config

- packages/mgt-components/src/components/sub-components/mgt-dot-options/mgt-dot-options.ts
> fix: revert dot-options to use fluent controls

- index.html
- packages/mgt-components/src/components/mgt-picker/mgt-picker.scss
- packages/mgt-components/src/components/mgt-picker/mgt-picker.ts
Closes #2421 
- Bugfix 
adds a new variable to set the max height of the mgt-picker list defaults the max height of the mgt-picker list to 380px
> fix: max picker list height

- packages/mgt-components/src/components/mgt-agenda/mgt-agenda.theme.scss
- stories/components/agenda/agenda.style.js
Closes #2455  
Bugfix
Removes mgt-agenda background color
> fix: remove mgt-agenda background colour

- packages/mgt-components/src/graph/graph.files.ts
Closes #2523
- Bugfix
- 
Returning a JSON parsed version of the cache for insights types. It was returning directly `fileList.files` but the files were still raw JSON.
> fix: Returning a JSON parsed version of the cache for insights types

- packages/mgt-components/src/components/mgt-person-card/mgt-person-card.scss
- packages/mgt-components/src/components/mgt-person-card/mgt-person-card.theme.scss
- packages/mgt-components/src/components/mgt-person-card/mgt-person-card.ts
Closes #2534  
- Bugfix 
removes fluent card and manually styles card background 
now uses --neutral-floating-layer as card background color
> fix: person card color

- index.html
- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
- packages/mgt-components/src/components/mgt-people-picker/strings.ts
- stories/components/peoplePicker/peoplePicker.a.js
- stories/components/peoplePicker/peoplePicker.properties.js
Closes #2542  
- Bugfix 
Makes single select mode show data and allow interaction after making a selection
> fix: people picker single select mode

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
- stories/components/peoplePicker/peoplePicker.properties.js
Closes #2576
- Bugfix 
fixes logic to populate selections to check length of arrays not existence of arrays
> fix: people picker default selections

- packages/mgt-components/src/components/mgt-file-list/mgt-file-list.ts
Closes #2588  
Bugfix
Fixes the bug that renders the files full view in person-card overview section
> fix: render the compact view of the files section in person-card overview section

- packages/mgt-components/src/components/mgt-agenda/mgt-agenda.graph.ts
- packages/mgt-components/src/components/mgt-agenda/mgt-agenda.ts
- stories/components/agenda/agenda.properties.js
Closes #2596 
- Bugfix 
uses a page iterator to get data when event-query is provided
updates event-query story to ensure more than a single page of data is requeested
> fix: use iterator to load events from event-query

- stories/overview.stories.mdx
Closes #2558  
Bugfix
Remove deprecated providers from storybook overview page
> fix: remove deprecated providers on storybook overview page

- .storybook/preview-body.html
- index.html
- packages/mgt-components/src/components/base-person-card-section.scss
- packages/mgt-components/src/components/mgt-agenda/mgt-agenda.scss
- packages/mgt-components/src/components/mgt-contact/mgt-contact.scss
- packages/mgt-components/src/components/mgt-file-list/mgt-file-list.scss
- packages/mgt-components/src/components/mgt-file/mgt-file.scss
- packages/mgt-components/src/components/mgt-person-card/mgt-person-card.scss
- packages/mgt-components/src/components/mgt-person/mgt-person.scss
- packages/mgt-components/src/components/mgt-picker/mgt-picker.scss
- packages/mgt-components/src/components/mgt-tasks-base/mgt-tasks-base.scss
- packages/mgt-components/src/components/mgt-tasks/mgt-tasks.scss
- packages/mgt-components/src/components/mgt-taxonomy-picker/mgt-taxonomy-picker.scss
- packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.scss
- packages/mgt-components/src/components/preview/mgt-search-results/mgt-search-results.scss
- packages/mgt-components/src/components/sub-components/mgt-arrow-options/mgt-arrow-options.scss
- packages/mgt-components/src/styles/shared-styles.scss
- stories/samples/general.stories.js
Closes #2641  
Bugfix
Removes setting --default-font-family on a per element basis
Applies --default-font-family to all elements in DOM
> fix: set custom css token --default-font-family to apply to all elements in DOM

- .github/workflows/pr-chat.yml
Closes #2750 
Sets the node version to 18.x for the react-contoso deploy workflow, will redeploy the sample app and allow us to validate that #2751 is working correctly when it is merged
> chore: use node 18.x to build react-contoso

- packages/mgt-react/src/MgtTemplateProps.ts
Closes #2753
- Bugfix
makes MgtTemplateProps generic to define the type for dataContext with a default of any type this provides backwards compatability and allows for specific typing of templates.
> fix: typing for template props data context

- packages/mgt-components/src/components/mgt-taxonomy-picker/mgt-taxonomy-picker.scss
- packages/mgt-components/src/components/mgt-taxonomy-picker/mgt-taxonomy-picker.theme.scss
- packages/mgt-components/src/components/mgt-taxonomy-picker/mgt-taxonomy-picker.ts
Closes #2728  
Bugfix
Update mgt-taxonomy-picker placeholder colors to match mgt-picker
> fix: update mgt-taxonomy-picker colors to match mgt-picker

- packages/mgt-chat/src/statefulClient/Caching/MessageCache.ts
- packages/mgt-chat/src/statefulClient/StatefulGraphChatClient.ts
Closes #2765 
- Feature
Adds code to update IndexDB when messages are received via web sockets
> feat: cache messages received via web sockets

- .github/workflows/pr-reporting.yml
Closes #2801 
ensures that any run of the CI pipeline will trigger the pr-reporting pipeline.
> chore: remove branch filter on ci test reporting workflow

- packages/mgt-chat/src/statefulClient/GraphConfig.ts
- packages/mgt-chat/src/statefulClient/GraphNotificationClient.ts
- packages/mgt-element/src/Graph.ts
Closes #2761 
- Feature
Adds a config based mechanism to allow developers to target the canary deployment of graph for faster testing of changes related to mgt-chat which are in flight from AGS and/or workload teams
> feat: add config switch to use cananry graph

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
- packages/mgt-react/src/generated/people-picker.ts
- stories/components/peoplePicker/peoplePicker.properties.stories.js
Closes #2794 
- Feature
add show-presence attribute to mgt-people-picker
BREAKING CHANGE: this changes the default behavior of mgt-people-picker to not show presence
Impact of breaking change is that now people picker usages will not show presence by default.
> feat!: add show-presence to mgt-people-picker

- packages/mgt-components/src/graph/graph.presence.ts
Closes #2808 
- Bugfix 
BREAKING CHANGE: applications which have previously requested presence.read.all and not presence.read will have a changed set of required scopes. This will require additional user consent or updating of pre-consented permissions when incremental consent is not enabled
> fix!: getUserPresence should only request presence.read

- packages/mgt-chat/src/statefulClient/GraphNotificationClient.ts
- packages/mgt-chat/src/utils/Timer.ts
- packages/mgt-chat/src/utils/timerWorker.ts
- packages/mgt-chat/tsconfig.json
Closes #2820 
- Feature
Adds a web worker based setInterval implementation
> feat: web worker based timers

- packages/mgt-components/src/graph/graph.presence.ts
This reverts commit 14e7a5687702de04e75fe45ff8fbf5d8ee4fe02b.
Closes #2824  
- Bugfix 
- [X ] All public APIs (classes, methods, etc) have been documented following the jsdoc syntax
> fix: revert getUserPresence should only request presence.read

- packages/mgt-components/src/graph/graph.people.ts
Closes #2738 
Bugfix
add space to filters template string in people-filters
> fix: add space to filters template string in people-filters

- samples/react-contoso/src/pages/ChatPage.tsx
Closes #2829 
- Bugfix 
CSS fix for using a people picker in a fluent v9 Dialog
New behvior:
> fix: display of flyout hidden by dialog

- index.html
- packages/mgt-components/src/index.ts
- packages/mgt/src/bundle/mgt-loader.js
- packages/mgt/src/exports.ts
- packages/mgt/src/index.ts
- packages/providers/mgt-mock-provider/src/index.ts
- packages/providers/mgt-msal2-provider/src/index.ts
Closes # 
- Feature 
all components must now be registered by developers to ensure that they render a convenience registeration function of registerMgtComponents can register all components mgt-loader registers all components when loading the underlying scripts into the browser
BREAKING CHANGE: Developers must explicitly call the register function for all components used in their application. Importing from the root of @microsoft/mgt-components no longer has an automatic registration side effect.
> feat: require explicit component registration

- packages/mgt-components/src/components/mgt-person/mgt-person.ts
Closes #2846
- Bugfix 
Ensures that data fetched is used in preference to the fallback details when loading presence. This was a regression introduced in #2786
> fix: presence fallback logic

- packages/mgt-components/src/components/mgt-person/mgt-person.tests.ts
- packages/mgt-components/src/components/mgt-person/mgt-person.ts
refactor mgt-person tests to await render events rather than the dom mutation
This should allow us to not specify a timeout.
> chore: refactor tests to await render events

- packages/mgt-chat/src/statefulClient/StatefulGraphChatClient.ts
Closes #2847 
- Bugfix 
Adds loop component content type to the unsupported content list.
> fix: add loop components as unsupported content types

- packages/mgt-chat/src/statefulClient/GraphNotificationClient.ts
- packages/mgt-chat/src/statefulClient/useGraphChatClient.ts
Closes #2860  
- Bugfix
moves sessionId to be held in sessionStorage to provide a stable id for the lifetime of the browser tab
> fix: sessionId management

- packages/mgt-chat/src/statefulClient/Caching/SubscriptionCache.ts
- packages/mgt-element/src/utils/CacheStore.ts
- packages/mgt-element/src/utils/CustomElement.ts
Closes #2863  
- Bugfix 
adds a transaction helper function to the CacheStore uses transactions to ensure atomic read and update when updating subscription cache data.
> fix: subscription caching

- packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
- stories/components/teamsChannelPicker/teamsChannelPicker.stories.js
Closes #2818 
Bugfix
Adds clearSelectedItem() method to clear selected channel in mgt-teams-channel-picker
> fix: add method to clear selected channel in mgt-teams-channel-picker

- packages/mgt-chat/src/components/NewChat/NewChat.tsx
Closes #2835  
- Bugfix
Set the `initialMessage` state to an empty string. This prevents it from being undefined, then being set to defined which causes the error.
> fix: set the initial message to an empty string in text area

- packages/mgt-chat/src/components/NewChat/NewChat.tsx
Closes #2807 
- Bugfix
Changed the placeholder and typed value's text size to `var(--type-ramp-base-font-size)` which is also used by the people-picker. This enables consistency in text sizes for the two components.
> fix: set the text size for NewChat to a global default value

- packages/mgt-components/src/components/mgt-contact/mgt-contact.ts
- packages/mgt-components/src/components/mgt-contact/strings.ts
- stories/components/personCard/personCard.stories.js
- stories/samples/general.stories.js
Closes #2887 
Corrects person-card section names in localization stories
> docs: fix person-card sections component names in localization

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #2891 
- Bugfix 
stops propagation of the keydown event from the people picker search input. 
this ensures that keystrokes which might trigger in pages shortcuts in SharePoint don't reach those event listener and break the component experience.
> fix: stop keydown from bubbling beyond people-picker

- .storybook/post-process-index-file.js
- index.html
Closes #2906 
- Bugfix
adds more to the CSP meta tag
> fix: add connect img and frame csp directives

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.scss
- stories/components/peoplePicker/peoplePicker.properties.stories.js
Closes #2915
- Bugfix 
allows the input to expand to show a larger placeholder
> fix: increase area for placeholder

- packages/providers/mgt-electron-provider/README.md
- packages/providers/mgt-electron-provider/src/Provider/ElectronContextBridgeProvider.ts
- packages/providers/mgt-electron-provider/src/Provider/index.ts
Closes #2618 
- Feature
This PR adds the `ElectronContextBridgeProvider` which adds support for Electron applications that use the isolated context and preload scripts. Developers using this provider **MUST** follow the steps included in the README to set up a `contextBridge` that correctly implements the `IContextBridgeImpl` interface. I've opted to pass the defined contextBridge object to the provider so that the developer is able to freely name the context bridge api without being forced to use "main" or "electronApi", etc.
> feat: add ElectronContextBridgeProvider

- packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
Closes #2665 
- Bugfix 
Adds a guard when attempting to access the content property that is reportedly causing an intermittent issue.
Note: I can't reproduce this issue so I'm making a best guess based on the fact Map.get can return undefined and there is only one unguarded access to a property to called content in the teams channel picker.
> fix: guard on non-existent result

- packages/mgt-components/src/components/mgt-organization/mgt-organization.scss
- packages/mgt-components/src/components/mgt-organization/mgt-organization.ts
Closes #2872 
- Bugfix 
Reformatted list of direct reports to have a single containing border:
> fix: direct reports list formatting

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
Closes #2899 
- Bugfix 
updated the keydown for the people-picker behavior to ensure that tab and enter can be used to enter email addresses when the allow-any-email attribute is present
> fix: enter email keypress behavior

- packages/mgt-components/src/graph/graph.user.ts
Closes #2919
- Bugfix
Add the ConsistencyLevel headers and `count(true)` to all calls using the `userFilters` when present.
> fix: adding headers and count on all potential advanced aad queries

- packages/mgt-components/src/components/mgt-picker/mgt-picker.ts
Closes #2907 
Feature
Allows the use of nested values in the mgt-picker component's key-name property, for example "fields.myCustomColumn"
Stories not updated but existing stories have been tested
> add support for nested values in mgt-picker key-name

- stories/components/person/person.react.stories.js
Closes #2977 
- Bugfix
Adding the right string vs. enums for our React stories!
> docs: fixing person string unions for react stories

- .github/workflows/push-preview-release.yml
- .github/workflows/push-release.yml
this will ensure that our v4 build can actually be published
Closes #3002 
> chore: update pipeline tag filters

- .storybook/addons/codeEditorAddon/codeAddon.js
Closes #3003 
- Bugfix
remove the check for an editor before setting the files object.
> fix: remove the check for an editor before setting the files object.

- packages/mgt-components/src/components/mgt-planner/mgt-planner.ts
Closes #2291 
- Bugfix 
Sets the add new task input to `autofocus` when you click/activate the add button.
> fix: add focus on input field when you click the button to add a new task

- samples/react-contoso/src/components/Header.tsx
- samples/react-contoso/src/pages/HomePage.tsx
Closes #2992  
Bugfix
Code style update (formatting)
> fix: clean-up react-contoso homepage

- packages/mgt-components/src/components/mgt-person/mgt-person.tests.ts
- packages/mgt-components/src/components/mgt-person/mgt-person.ts
- packages/mgt-components/src/components/mgt-person/strings.ts
- packages/mgt-element/src/utils/LocalizationHelper.ts
adds extended tests for Localization on mgt-person
removes the initals property from the default set of strings for mgt-person
Closes #2989 
- Bugfix
> fix: typing for LocalizationHelper.strings

- packages/mgt-components/src/components/mgt-planner/mgt-planner.ts
- stories/samples/general.stories.js
Closes #2302  
- Bugfix
- Set the add button to disabled until the task name is provided.
- fix planner localization string
> fix: set add button to disabled until task name is provided

- packages/mgt-chat/src/components/Chat/Chat.tsx
- packages/mgt-chat/src/components/ChatAvatar/BotAvatar.tsx
- packages/mgt-chat/src/components/ChatAvatar/ChatAvatar.tsx
- packages/mgt-chat/src/components/ChatHeader/OneToOneChatHeader.tsx
- packages/mgt-chat/src/components/Context/BotInfoContext.ts
- packages/mgt-chat/src/statefulClient/BaseStatefulClient.ts
- packages/mgt-chat/src/statefulClient/BotInfoClient.ts
- packages/mgt-chat/src/statefulClient/GraphNotificationClient.ts
- packages/mgt-chat/src/statefulClient/StatefulClient.ts
- packages/mgt-chat/src/statefulClient/StatefulGraphChatClient.ts
- packages/mgt-chat/src/statefulClient/buildBotId.ts
- packages/mgt-chat/src/statefulClient/chatOperationScopes.tests.ts
- packages/mgt-chat/src/statefulClient/chatOperationScopes.ts
- packages/mgt-chat/src/statefulClient/graph.chat.ts
- packages/mgt-chat/src/statefulClient/useBotInfo.ts
- packages/mgt-chat/src/utils/reduceScopes.tests.ts
- packages/mgt-chat/src/utils/rewriteEmojiContent.tests.ts
- packages/mgt-chat/src/utils/rewriteEmojiContent.ts
- packages/mgt-element/src/Graph.ts
Closes #2947
Closes #3060 
Closes #3068 
- Bugfix
- Feature
sets up a React Context + Provider model for getting Bot based data via a shared Stateful Client
refactor to create a base class for stateful clients
creates a new component for rendering chat avatars that can handle bots
stop creating two instances of the notification client
remove contenteditable attribute from emjoi html
> feat: bot names and avatars

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
- stories/components/peoplePicker/peoplePicker.properties.stories.js
Closes #3066  
Bugfix
Disables input on people-picker single-select mode in the case of default selected user Ids and group Ids
> fix: disable input in single select mode and default userIds and groupIds

- stories/components/peoplePicker/peoplePicker.properties.stories.js
Closes #3125 #3126 #3127
- Bugfix 
Reworks the dynamic groupid story for people picker to address a11y concerns
> docs: fix dynamic group story accessibility concerns

- packages/mgt-components/package.json
- packages/mgt-element/package.json
- packages/mgt-react/package.json
- packages/mgt-spfx-utils/package.json
- packages/mgt/package.json
- packages/providers/mgt-electron-provider/package.json
- packages/providers/mgt-mock-provider/package.json
- packages/providers/mgt-msal2-provider/package.json
- packages/providers/mgt-proxy-provider/package.json
- packages/providers/mgt-sharepoint-provider/package.json
- packages/providers/mgt-teamsfx-provider/package.json
also normalizes git urls in package.json as expected for publishing
> fix: version bump

- stories/components/peoplePicker/peoplePicker.style.stories.js
> fix(a11y): correct people-picker placeholder luminosity contrast

- stories/components/personCard/personCard.style.stories.js
> fix(a11y): correct mgt-person-card line-3 text color contrast in custom styles

- .storybook/manager.js
- packages/mgt-components/src/components/mgt-teams-channel-picker/mgt-teams-channel-picker.ts
> fix: mgt-channel-picker icons tab behavior

- .storybook/manager.js
Closes #3075  
- Bugfix
Rewrites the title attribute value for the screen sizing buttons
Sets the aria-label attribute value to the title value of the sizing buttons
> fix(a11y): set the title and aria-label for the screen sizing buttons

- packages/mgt-components/src/components/mgt-file-list/mgt-file-upload/mgt-file-upload.scss
- packages/mgt-components/src/components/mgt-file-list/mgt-file-upload/mgt-file-upload.ts
- packages/mgt-components/src/components/mgt-file-list/mgt-file-upload/strings.ts
Closes #3110  
- Bugfix
Created custom events to be fired on successful or failed file upload attempts
Focus on the uploaded file
Set aria-label text to narrate the file name and status of upload
> fix(a11y): focus on uploaded file and narrate status

- stories/components/personCard/personCard.properties.stories.js
> docs: add global person-card config story

- release-please-config.json
> chore: fix extra files paths in release-please config

- packages/mgt-components/src/components/mgt-organization/mgt-organization.scss
Closes #3261  
- Bugfix
Added a 4px padding, top and bottom of elements in the direct reports list.
> fix:add padding to the list of direct reports in person-card

- packages/mgt-components/src/components/mgt-person-card/mgt-person-card.graph.ts
- packages/mgt-components/src/components/mgt-person/mgt-person.ts
- packages/mgt-components/src/graph/cacheStores.ts
Closes #3260  
- Bugfix
- Added caching of the response data from the batch requests performed for the card state.
- If a person has `person-card` attribute set, do a call for card state batches . This will hit the cache first, if no cache is found, the network call is made and the response is cached. This enable any person card interaction on person to be faster as the data is already in cache.
Maybe cache to a lower time limit to avoid stale data on updated sections like `messages`?
> fix: implement caching on the card state for person card

- packages/mgt-components/src/components/mgt-people-picker/mgt-people-picker.ts
- stories/components/peoplePicker/peoplePicker.properties.stories.js
Closes #3201  
Bugfix
Display default selected users and groups while disabling suggestions
> fix: display default selected users and groups while disabling suggestions

- packages/mgt-components/src/components/mgt-person-card/mgt-person-card.graph.ts
- packages/mgt-components/src/graph/graph.people.ts
- samples/react-contoso/src/pages/HomePage.tsx
- stories/components/people/people.react.stories.js
Closes #3172  
Working repro: https://stackblitz.com/edit/mgt-8925-1jlicc?file=src%2Fmain.tsx,src%2FApp.tsx,package.json
> docs: add react peopleQueries story

- packages/mgt-chat/src/statefulClient/Caching/MessageCache.ts
- packages/mgt-chat/src/statefulClient/StatefulGraphChatClient.ts
Closes #3031
Closes #3032  
Bugfix
Check for unique cached messages to prevent mixup, to fix issue in rapid chat changes resulting in incorrect chatID > chat message cache mapping.
How to test: Checkout the branch and run the reac-chat app sample, test out changes.
> fix: cached message state mixup

- packages/mgt-components/src/graph/graph.groups.ts
- stories/components/peoplePicker/peoplePicker.properties.stories.js
Closes #3288  
Bugfix
Add top query parameter on batch request to limit group results
> fix: show max while picking multiple groups

- packages/providers/mgt-msal2-provider/src/Msal2Provider.ts
Closes #3070 
Bugfix
Handle errors when user cancels sing-in popup, or tries to login when there's an already existing login process.
How to test: Ensure that you initialize MSAL2 with  loginType: LoginType.Popup and first try to login and close the popup, then second click the sign in button multiple times without closing the popup.
> fix: handle popup login errors

- packages/mgt-components/src/graph/cacheStores.ts
- packages/mgt-components/src/graph/graph.groups.ts
Closes #3358 
- Bugfix
Improve the Custom type `GroupType` handling by asserting it's an array. This looks redundant but I have no idea why the passed typed in the functions' argument is causing errors when you use array functions on it.
> fix: change group type handling and cache key construction

- stories/components/searchResults/searchResults.templating.stories.js
Closes #3415  
Feature
Add default and no-data template stories for mgt-search-results
> fix(search-results): add templating stories

- packages/mgt-components/src/components/mgt-file-list/mgt-file-list.ts
Closes # [3413](https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/3413)
- Bugfix
- Fixed broken pagination when filtering by extension. This was caused by `this._preloadedFiles` not being updated after fetching data in `mgt-file-list.ts`. 
- Additionally, files will now be fetched using the maximum pagination size because the pagination is done on the client side here. after everything is fetched, pagination will use the user-defined page size normally.
> fixed file list pagination not working when filtering file extensions

- stories/components/person/person.properties.stories.js
- stories/components/planner/planner.style.stories.js
Closes #3370
Closes #3372   
Bugfix
Corrects contrast ratio in elements
1. Open Desktop Accessibility Insights.
2. Go through the provided link and ensure the mgt-planner `custom css properties` story and mgt-person `More Examples` story have the required contrast ratios between the previously flagged elements.
> fix(a11y): improve contrast ratio on component style stories

- packages/mgt-components/src/components/mgt-person/mgt-person.ts
- stories/components/person/person.html.stories.js
Closes #3375  
Bugfix
Go through the story here: https://mgt.dev/next/pr/3420/?path=/story/components-mgt-person-html--events and ensure the lines are keyboard accessible
> fix(a11y): add keyboard accessibility in mgt-person line event story

- .github/workflows/push-release.yml
The TeamsFX auth provider only relies on the interface, so if there are no changes to the TeamsFX auth provider, we do not need to track the version of the Graph Toolkit any more. So remove this notification.
> chore: remove notification to teams toolkit
